= Configure the Platform Cache
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Improve the performance of pages and components in your Salesforce Experience Cloud site by using the https://help.salesforce.com/articleView?id=data_platform_cache.htm&type=5[platform cache, role=external, window=blank].

The platform cache has two parts: a session cache that holds data specific to one user and their session, and an organization cache that holds data accessed by multiple users in the organization.

Cached objects include:

Applications:: Details of the client applications of the users
API Versions:: Basic details of API versions from Exchange
API Documentation:: API version information and documentation pages
API Instances:: Available instances of each published API version
Categories:: Categories defined in Exchange for organizing APIs
API Categories:: Category values that have been applied to APIs in Exchange
API Tier Limits:: Service Level Access (SLA) tier limits, such as the number of requests an API can make
API Query:: Responses of the "Try It" operation in the API Console

Set which parts are enabled and the amount of time the cache keeps each type of data:

. Log in to your Salesforce organization.
. In *Setup*, click *Custom Metadata Types*.
. Next to the label *ACM Platform Cache Metadata*, click *Manage Records*.
. Next to the label *ACM Configuration*, click *Edit*.
. Use the *Session Cache Enabled* and *Organization Cache Enabled* checkboxes to enable or disable the corresponding cache.
. Set the number of seconds that cached data remains in the cache for applications, API versions, documentation content, instances, categories and category values, tier limits, and queries.
. If you want to see the minimum and maximum number of seconds for each entity, hover over the question mark (?) next to each field name.
. If you want to disable caching of an entity, set that field to zero seconds.
. Click *Save*.

Cache size defaults to zero. To finish configuring the caches, set the cache size:

. Log in to your Salesforce organization.
. In *Setup*, click *Platform Cache*.
. Click the `ACMCache` partition.
. Click *Edit*.
. Set the size of each cache (in megabytes) in the *Organization* field.
+
The sum of the sizes of the session cache and the organization cache cannot be more than your organization's cache capacity, as determined by your xref:licensing-overview.adoc[license].
. Click *Save*.

The new configuration is effective immediately.

To see how much of each cache is in use, you can click *Recalculate*.

== See Also

* https://help.salesforce.com/articleView?id=data_platform_cache.htm&type=5[Salesforce Platform Cache documentation, role=external, window=blank]
* https://trailhead.salesforce.com/content/learn/modules/platform_cache[Platform Cache Basics module on Trailhead, role=external, window=blank]
