= Configure ACM
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

NOTE: Installing, updating or configuring API Community Manager must be done by a user account with the *System Administrator* profile in the ACM Salesforce organization.

The following sections guide you through API Community Manager configuration:

* <<authenticate-the-external-data-source>>
* <<give-permissions-to-acm-community-manager>>
* <<verify-portal-account-owner-role-setting>>
* <<configure-eu-account>>

* <<communities>>

** <<create-a-community>>
** <<customize-a-community>>
** <<enable-forums>>
** <<define-moderation-rules-for-forums>>
** <<publish-a-community>>

* <<users>>

** <<configure-guest-user-access>>
** <<configure-registered-users>>
** <<set-permissions-for-unauthenticated-users>>
** <<add-self-register-custom-component-to-register-page>>
** <<enable-external-user-registration>>

*** <<assign-the-profile-to-new-community-members>>
*** <<create-the-account-for-your-community>>
*** <<configure-your-login-and-registration-page>>

** <<set-up-an-admin-approval-process-for-new-user-creation>>

*** <<specify-approval-process-parameters>>
*** <<create-an-approval-step>>
*** <<create-a-final-approval-action>>
*** <<activate-the-approval-process>>

** <<create-a-public-group>>
** <<create-sharing-settings>>
** <<set-up-user-impersonation>>

To open API Community Manager, first select the *App Launcher*. The App Launcher icon
is the first icon displayed in the main navigation bar. Then select *API Community Manager*.

== Authenticate the External Data Source [[authenticate-the-external-data-source]]

The external data source specifies how to access the MuleSoft Anypoint system.

. Search for *External Data Source* in the *Quick Find* box and then select *External Data Sources*.
. Select *Exchange* and then select *Edit*.
. Update *Identity Type* to *Named Principal*.
. Update *Authentication Protocol* to *OAuth 2.0*.
. Update *Authentication Provider* to *Anypoint*.
. Select *Save*. The *Anypoint Login* page is shown.
. Log in to the Anypoint Platform.
. Search for *External Data Source* in the *Quick Find* box and then select *External Data Sources*.
The *External Data Sources* information for Exchange shows the *Authentication Status* is *Authenticated*.
If you experience problems, check the Auth. Provider callback endpoint and your domain
configuration in xref:reference.adoc[Configuration Reference].
. Search for *Named Credentials* in the *Quick Find* box and then select *Named Credentials*.
. Select *Edit*.
. In the *Authentication* section, enter the Anypoint username and password in the *Username* and
*Password* fields, respectively.
. Select *Save*.

== Give Permissions to ACM Community Manager [[give-permissions-to-acm-community-manager]]

If you cannot view ACM Community Manager content in the *Lightning Experience App Manager*, you must
add the *ACM Administrator* tab from the App Manager in *Setup*:

. In *Setup*, search for App Manager using the *Quick Find* box, select *API Community Manager*, and then edit it.
. Navigate to *Navigation Items*, highlight *ACM Administrator*, and move it to the *Selected Items* column. Select *Save*.
. Log out and log back in to your Salesforce organization.
. In the *ACM Administrator* tab, select *Manage APIs*.
. Select the APIs you want to show in the Community portal using *Add to Community*.
. As needed, change the description, icon, visibility and marketing page of each API with the *Edit* button
in the *Community* section.

== Verify Portal Account Owner Role Setting [[verify-portal-account-owner-role-setting]]

. Navigate to *Setup -> Users* and select your username.
. Set the appropriate *Role*.
. Select *Save*.

== Configure EU account [[configure-eu-account]]

If you have an EU account, which is 
https://docs.mulesoft.com/eu-control-plane/platform-access-eu[hosted within the EU, role=external, window=_blank], 
you must authenticate, set up and configure your domain, and manage your APIs, applications, and related data 
using the following URL: `eu1.anypoint.mulesoft.com`. This is because the EU control plane stores all MuleSoft data 
within the EU, and you cannot access EU account data and information using the US Anypoint Platform control plane URL. 

To use API Community Manager in an EU region, you must change all occurrences of `anypoint.mulesoft.com` 
to include a `eu1` prefix. For example: you must update the `https://anypoint.mulesoft.com/odatabridge/odata.svc` 
External Data Source configuration URL to: `https://eu1.anypoint.mulesoft.com/odatabridge/odata.svc`. 

The following list contains the required updates:

* Named Credentials URL when you <<authenticate-the-external-data-source>>: Change `https://anypoint.mulesoft.com` to `https://eu1.anypoint.mulesoft.com`.
* *Authorize Endpoint URL* when you Configure the Auth Provider during <<set-up-user-impersonation>>:
Change
`https://anypoint.mulesoft.com/accounts/oauth2/authorize` to `https://eu1.anypoint.mulesoft.com/accounts/oauth2/authorize`.
* *Token Endpoint URL* when you Configure the Auth Provider during <<set-up-user-impersonation>>: 
Change `https://anypoint.mulesoft.com/accounts/oauth2/token` 
to `https://eu1.anypoint.mulesoft.com/accounts/oauth2/token`.
* Remote site settings : Add the new site `AnypointEu` with the URL `https://eu1.anypoint.mulesoft.com`.
* CSP trusted sites: Add the following sites:

** `https://eu1.anypoint.mulesoft.com` 
** `https://exchange2-file-upload-service-kprod-eu.s3.eu-central-1.amazonaws.com`
** `https://exchange2-asset-manager-kprod-eu.s3.amazonaws.com`

== Communities [[communities]]

=== Create a Community [[create-a-community]]

. If you are not familiar with Communities, refer to the https://help.salesforce.com/articleView?id=networks_resources.htm&type=5[Salesforce Community Overview, role=external, window=blank].
. Navigate to *Setup*.
. In the *Quick Find* box, enter *All Communities* and then select *All Communities*.
. Select *New Community*. All communities templates are listed.
. Choose *API Community Manager Template*.
. On the *API Community Manager* page, select *Get Started*.
. Enter a *Name* and a *URL*.
. Select *Create*.
. After the new community is created, select *Builder* to modify the community appearance and components if needed.
. Navigate to *Administration* and select *Activate Community*.

=== Customize a Community [[customize-a-community]]

Refer to xref:brand-intro.adoc[Brand and Customize Your API Community].

=== Enable Forums [[enable-forums]]

. In the Salesforce *Settings*, select *Display additional fields*.
. Enable forums.
. In the ACM administrator interface, select *Manage CMS Content*.
. Select the *Topics* tab.
. Select *Navigational Topics*.
. Create topics for your community forums.

=== Define Moderation Rules for Forums [[define-moderation-rules-for-forums]]

. Navigate to your Community Workspace.
. In the main navigation bar, select *Moderation -> Rules*.
. Create a rule. At a minimum, enter information for the *Name* and *Unique Name* fields in the *Details* section.
. Enter information for all fields in the *Rule Conditions* section.

IMPORTANT: Verify the *Activate Rule* check box is active when saving your changes.

=== Publish a Community [[publish-a-community]]

. In the Community Builder, select *Publish*.
. In the *Publish Your Community* page, select *Publish*.
. You will receive an email with this information:
`Congratulations! User was published successfully and is now live on the following domain(s):
https://exampledomain-developer-edition.na91.force.com/mydomain/s`

== Users [[users]]

After you create a community, you must create the different user profiles for your community guests and members, so that you can control access to and visibility of APIs and content.

=== Configure Guest User Access [[configure-guest-user-access]]

In this section, you create the profile for guest community users. Users that are not signed-in are guest users.

.. Navigate to *Setup*.
.. In the *Quick Find* box, enter *Users*.
.. Select *Profiles*.
.. In the *Profiles* page, select *Clone* next to the *Customer Community User* profile.
.. In the *Profiles* page, enter `ACM [ Community Name ] User` for *Profile Name*.
.. Select *Save*.

. Change permissions for *External Objects* and *Custom Objects*.
.. Navigate to *Field-Level Security*.
.. In the *Custom Field-Level Security* section, repeat the following step for the *AnypointApiVersions*,
*AnypointApplications*,
*AnypointContracts*,
*AnypointApiInstances*, and
*CommunityApi* items:
.. Select *View* and then *Edit* .

// Which fields need to be updated?

=== Configure Registered Users [[configure-registered-users]]

In this section, you create the profile for members of your community. Users that are signed-in are members.

. Navigate to *Setup* -> *Communities* -> *Communities Settings*.
. Scroll to *Sharing Sets* and select *New*.
. In the *Sharing Set Edit* section, update *Label* with `[Community Name] Sharing Set`. Select *Save*.
. Select *ACM [Community name] User* from *Available Profiles* and add it to *Selected Profiles*.
. Select *CommunityApi* from *Available Objects* and add it to *Selected Objects*.
. In the *Action* column, select *Set Up*.
. Enter the information required in the *Access Mapping for CommunityApi* page.

// More info needed?

=== Set Permissions for Unauthenticated Users [[set-permissions-for-unauthenticated-users]]

. In the Community Builder, navigate to *Settings* -> *General* and select the *Public can access the community* check box.
. Navigate to *Settings* -> *SEO* and select *Guest User Profile*. Make the necessary changes.
. Navigate *Settings -> General* and select *Guest User Profile*.
. Select *Edit*.
. Enable *Read*, *Create*, *Edit*, and *Delete* permissions to the external objects listed in the
*External Object Permissions* section.
. Select *Save*.
. Change the permissions for the following objects in the *Custom Field-Level Security* section:

** *AnypointApiInstances*

*** All fields: *Read Access*
*** *Display URL*: *Edit Access*
*** *External ID*: *Edit Access*

** *AnypointApiTiers*

*** *Display URL*: *Read Access* and *Edit Acccess*
*** *External ID*: *Read Access* and *Edit Acccess*

** *AnypointApiVersions*

*** *Display URL*: *Read Access* and *Edit Acccess*
*** *External ID*: *Read Access* and *Edit Acccess*

** *AnypointApplications*

*** *Display URL*: *Read Access* and *Edit Acccess*
*** *External ID*: *Read Access* and *Edit Acccess*

** *AnypointContracts*

*** *Display URL*: *Read Access* and *Edit Acccess*
*** *External ID*: *Read Access* and *Edit Acccess*

** *CommunityApi*

*** *ApiID*: *Read Access* and *Edit Acccess*
*** *AssetType*: *Read Access* and *Edit Acccess*
*** *AssetVersion*: *Read Access* and *Edit Acccess*
*** *CommunityApi Name*: *Read Access* and *Edit Acccess*
*** *Created By*: *Read Access*
*** *Last Modified By*: *Read Access*
*** *Name*: *Read Access* and *Edit Acccess*
*** *Owner*: *Read Access* and *Edit Acccess*
*** *Visibility*: *Read Access* and *Edit Acccess*

=== Add Self Register Custom Component to Register Page [[add-self-register-custom-component-to-register-page]]

The self-register component allows your users to self-register in your community.

NOTE: Follow these steps only if you created a community NOT using the ACM Template. The Self Register custom
component is automatically added to the Register page if you created a community using the ACM Template.

. In the Community Builder, navigate to the *Register* page.
. Remove the standard *Self Registration* component by selecting the delete
icon next to it.
. Navigate to *Components*, search for *Self Register* and add it to the page.

// More info needed?

=== Enable External User Registration [[enable-external-user-registration]]

==== Assign the Profile to New Community Members [[assign-the-profile-to-new-community-members]]

. Navigate to *Community Administration* -> *Members*.
. Select *All* from the Search drop-down.
. Add *ACM [Community Name] User* to *Selected Profiles*.
. Select *Save*.

==== Create the Account for Your Community [[create-the-account-for-your-community]]

. Navigate to *App Launcher -> Accounts*.
. Enter `ACM Registered Users` in *Account Name*.
. Select *Save*.

==== Configure Your Login and Registration Page [[configure-your-login-and-registration-page]]

. Navigate to *Community Administration -> Login & Registration*.
. As needed, update the *Login Icon* information in *Branding Options*.
. On the *Registration Page Configuration* page:

.. Select *Allow external users to self-register*.
.. Select *Community Builder Page* for *Registration Page Type* and select *Register*.
.. Select *ACM Registered Users* in *Profile*.
.. Select *ACM [ Community Name ] Account* in *Account*.
.. Select *Save*.

=== Set Up an Admin Approval Process for New User Creation [[set-up-an-admin-approval-process-for-new-user-creation]]

==== 1. Specify Approval Process Parameters [[specify-approval-process-parameters]]

. Search for `Approval Processes` in the *Quick Find* box and then select *Approval Processes*.
. Select *Self Register User Request* in the *Manage Approval Processes For:* drop-down.
. Select *Use Standard Setup Wizard* in the *Create New Approval Process* drop-down.
. In the wizard, enter the following information:

.. In *Step 1. Enter Name and Description*, enter the following information:

*** *Process Name*: `Approve Registration`.
*** *Description*: Enter information that applies to your process.

.. In *Step 2. Specify Entry Criteria*, enter the following information:

... In the *Field* section, set the following values for `SelfRegisterUserRequest: Approved`:

**** *Operator*: `equals`
**** *Value*: `False`
.. In *Step 3. Specify Approver Field and Record Editability Properties*:

... Review the information in *Self Register User Requests*:

**** Leave the default values.
**** Verify *Record Editability Properties* shows *Administrators ONLY can edit records during the
approval process* is selected.
.. In *Step 4. Select Notification Templates*:

... Verify *Approval Assignment Email Template* is set to  *Registration Request*.
.. In *Step 5. Select Fields to Display on Approval Page Layout*:

... Add `Self Register User Request Name` and `Owner` to *Selected Fields*.
... Select the *Display approval history information in addition to the fields selected above.* check box.
.. In *Step 6. Specify Initial Submitters*:

... Add *Self Register User Request Owner* to the *Allowed Submitters* column.

==== 2. Create an Approval Step [[create-an-approval-step]]

. After you create the Approval Process:

** If you are prompted to add an Approval Step:

... Select *Yes, I'd like to create an approval step now*.
... Select *Go!*.

** If you are not prompted to add an Approval step:

... Search for *Approval Processes* in the *Quick Find* box.
... Select *Approve Registration* (the approval that you created).
... In the *Approval Steps* section, select *New Approval Step*.

. In the *Step 1: Enter Name and Description* section:

.. Enter `Step 1` in *Name*.
.. Select *Next*.

. In the *Step 2: Specify Step Criteria* section, select *Next*.
. In the *Step 3 - Select Assigned Approver* section:

.. Select *Let the submitter choose the approver manually*.
.. Select *Save*.

==== 3. Create a Final Approval Action [[create-a-final-approval-action]]

. On the *Self Register User Request: Approve Registration* page, navigate to *Final Approval Actions* and select *Add New*.
. Select *Field Update*.
. In the *Field Update Edit* section, enter the following values:

** *Name*: `Create User`
** *Field to update*: `Approved`
** *Re-evaluate Workflow Rules after Field Change*: Select the check box.
** *Checkbox Options*: `True`.

. Select *Save*.

==== 4. Activate the Approval Process [[activate-the-approval-process]]

. On the *Approve Registration* page, select *Activate* and confirm.
. In the Community Builder, navigate to the *Register* page, remove the default register component, and
select ACM *Self Register*.
. Verify the Approved Registration and set *Approver Id*.
. Navigate to Salesforce Setup.
. Search for `Users` in the *Quick Find* box and then select *Users*.
. Select the full name of the user who you want to be the approver.
. The ID is contained in the URL of the User detail page you are currently
viewing. Remove the first 2 characters and paste the remaining information in
the *Approver Id* field. For example, if the unique ID is `2F0052D000001QpG1`,
paste `0052D000001QpG1` in the *Approver Id* field.

=== Create a Public Group [[create-a-public-group]]

. Navigate to *Setup -> Users -> Public Groups*.
. Select *Create New View*.
. In the *Label* field, enter `[Community Name] Public Group`.
. In the *Search* field, enter *Users*.
. In the *Selected Members* column, enter `User: [Community Name] Site Guest User`.
. Select *Save*.

=== Create Sharing Settings [[create-sharing-settings]]

These settings use the Public Group that you previously created.

. Navigate to *Setup -> Security -> Sharing Settings*.
. Scroll to and select *CommunityApi Sharing Rules*.
. Select *New*.
. In the *Rule Name* section, update *Label* with `[Community Name] Guest`.
. In the *Select your rule type* section, select `Based on criteria`.
. In the *Select which records to be shared* section, add the following criteria:

.. *Field*: `Community Name` *Operator*: `equals` *Value*: `[Community Name]`
.. *Field*: `Visibility` *Operator*: `equals` *Value*: `Public`

. In *Select the users to share with*: enter *Share with*: `Public Groups` and `[Community Name] Public Group`.
. In *Select the level of access for the users*, select *Read Only*.
. Select Save.
. Switch to Salesforce Classic.
. Select the plus (+) button.
. In *View*, select *Content* and then select *Libraries*.
. In the *Manage Libraries* section, select *Asset Library*.
. In the *Members* section, select *Add Members*.
. In the *Edit Library Membership Wizard*, select `Public Groups` from the *Search* drop-down and add the
public group previously created.
. Assign the *Viewer* Permission and select *Save*.

// In the steps above how do users switch to Salesforce Classic?

=== Set Up User Impersonation [[set-up-user-impersonation]]

Set up user impersonation to connect ACM with the Anypoint Platform.

. Create a Connected App

.. In Anypoint Platform, navigate to *Access Management* -> *Applications* -> *Create New Application*.
.. Provide the following information:

*** *Application Name*: Enter a name.
*** *Redirect URIs*: This URL can be found in the Authentication Provider configuration. Navigate
to *Salesforce Setup* -> *Auth. Providers* -> *Anypoint* -> *Callback URL*.
*** *User Grant Types*
**** *Authorization Code*: Checked.
**** *Refresh Token*: Checked.
**** *Full Access*: Checked
**** *Background Access*: Checked.

.. Select *Create Application*.

... Curl example:

    `curl -X POST \
      https://anypoint.mulesoft.com/accounts/api/connectedApplications \
      -H 'Accept: */*' \
      -H 'Accept-Encoding: gzip, deflate' \
      -H 'Authorization: Bearer ***token***' \
      -H 'Host:anypoint.mulesoft.com' \
      -d '{"client_name":"SalesforceApp","grant_types":["authorization_code","refresh_token"],"redirect_uris":["https://OrgDomain.my.salesforce.com/services/authcallback/Anypoint"],"scopes":["full","offline_access"],"public_keys":[]}`


. Configure Auth Provider

.. From the Salesforce interface, navigate to *Setup* -> *Auth. Providers* -> *Anypoint* -> *Edit*.
.. Provide the following information:
... *Consumer Key*: The application ID of the Connect App created in Anypoint.
... *Consumer Secret*: The application secret of the Connect App created in Anypoint.
... *Authorize Endpoint URL*: `https://anypoint.mulesoft.com/accounts/api/v2/oauth2/authorize`
... *Token Endpoint URL*: `https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token`
... *Default Scopes*: `full offline_access`.

    NOTE: Remember to associate the External Datasource with this Auth provider.

. Configure IDP

** Using SAML, an IDP must be configured in both Anypoint and Salesforce. You can use Salesforce as an IDP.

.. Setting up SAML

... Register an app for SAML in Salesforce:

.... Navigate to the *Setup* page.
.... Select *App Manager*.
.... Select *New Connected App*.
.... Provide the following Basic Information:

***** Connected App Name : This automatically populates the API Name, such as `Anypoint`.
***** Contact Email
.... Under Web App Settings:

..... Provide the *Start URL*: `https://anypoint.mulesoft.com/accounts/login/<your_anypoint_domain_name>` or the location
where you want users to be sent in the Anypoint Platform.
..... Select *Enable SAML*.
.... Provide any string as *Entity Id*. This is also the Audience configuration in the Anypoint Platform.
.... Provide the *ACS URL*. SAML assertions are sent to the ACS URL. For Anypoint:
`https://anypoint.mulesoft.com/accounts/login/receive-id`.
.... Select *Enable Single Logout*.
.... Provide *Single Logout URL*: `https://anypoint.mulesoft.com/accounts/logout/receive-id`.
.... Set *Single Logout Binding* to *HTTP Post*.
.... Set *Subject Type* to *Username*.
.... Set *Name ID* Format to *unspecified nameID format*.
.... Set *Issuer* to *salesforce_org_domainname*.
.... Set *IdP Certificate* to *Default IdP Certificate*.
.... Select *Save*.

... Set Up Custom Attributes:

**** By default, Salesforce does not send first name and last name attributes, so you must add them.

.... Select *Manage* for your app.
.... Scroll to *Custom Attributes*.
.... Select *New*. Type `firstname`. Click *Insert Field*. Select *$User >* -> *First Name* -> *Insert* -> *Save*.
.... Select *New*. Type `lastname`. Click *Insert Field*. Select *$User >* -> *Last Name* -> *Insert* -> *Save*.

... Configure Anypoint account with external identity with SAML:

.... Navigate to your Salesforce app enabled for SAML and select *Manage* to see all the URIs to be used to set up
external identity in Anypoint. Make a note of these URIs for quick reference.
.... Switch to your Anypoint account. Navigate to
*Access Management* -> *External Identity* -> *Identity Management* -> *SAML 2.0*.
.... Set *Sign On URL* to *IdP-Initiated Login URL*.
.... Set *Sign Off URL* to *Single Logout Endpoint*.
.... Set *Issuer* to match the Salesforce account: `salesforce_org_domainname`.
.... To find your Public Key, find Identity Provider, select *Download certificate*, and
open the certificate in a text editor. Copy all of the content and paste it into the *Public Key* field.
Alternatively, you can download metadata from the Salesforce app and extract the certificate from it.
.... Set *Audience* to match the *Entity Id* you set in the Salesforce account.
.... Select *Save*.

. Configure and Authorize ODATA Bridge to Perform Impersonation

** This final step requires a private key or a certificate, and a keystore (JKS) containing that key or certificate. Use the same certificate that Salesforce IDP uses.

.. In *Salesforce Setup*, search for *Certificate and Key Management* using the *Quick Find* box .
.. Select *Export to Keystore*.
.. Enter a new Password.
.. Select *Export*.

.. Import Keystore in Secrets Manager

... In Anypoint, go to *Access Management* -> *Environments*.
... Select *Add Environment* and provide the following information:

**** Set *Environment Name* to `ACM`.
**** Select *Production*.
... Select *Create*.
... Select *Users*.
... Select your user.
... Select *Secrets Manager*.
... Set *Environment* to the newly created environment: `ACM`.
... Select all permissions in *Permissions*.
... Select the plus button.
... To apply these changes, log out and then log back in.
... In Anypoint, select *Secrets Manager*.
... Select the desired environment using the environment switcher.
... Select *Create Secret Group*.
... Set *Name* to *Certificates*.
... Select *Secret Group Downloadable*.
... Select *Save*.
... Select *Keystore*.
... Select *Add Keystore*.
... Provide the following information:

**** *Name*: Enter `Impersonation`.
**** *Type*: Enter the type of your keystore, which is typically JKS.
**** *Keystore File*: Choose your keystore file, which is typically the file you exported from Salesforce.
**** *Keystore Passphrase*: Enter the exported Keystore.
**** *Alias*: Choose the corresponding alias to your key or certificate.
**** *Key Passphrase*: Create a new Keystore.

... Select *Save*.
... Select *Secret Groups*.
... Select *Finish* on the recently created secret group and confirm the operation.

*** For detailed information about creating secret groups and adding certificates, refer to
https://docs.mulesoft.com/anypoint-security/asm-secret-group-creation-task#create-a-secret-group[Create a Secret Group (Anypoint Platform), role=external, window=_blank].

.. Mapping Community User to Anypoint Role

... Navigate to *Access Management* and select *Roles*.
... In *Exchange Viewers*, set a new External group called `Community User` and save it.

... *IMPORTANT*: If you choose to use another key or certificate for the impersonation feature,
you must add this key in the External Identity configuration on Anypoint, as shown in the following steps:

.... In Anypoint, select *Access Management* -> *External Identity* -> *Edit*.
.... Add your key in *Public Key*:

..... Copy the key with no line breaks.
..... After the key displayed in the *Public Key* field, add a comma (,) and then paste in the new key.
..... Select *Save*.

// For more information about this feature, see the User Impersonation link section of the architecture documentation.
