= The ACM Consumer Developer Experience
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Many companies use Salesforce Community Cloud to build branded and customized online portals to offer their products to their customers. In the same way, your company can use API Community Manager to build branded and customized online portals to offer their APIs to the internal and external software developers who write code that uses and consumes those APIs.

Just as a customer interacts with your company's site, these consumer developers will arrive at your company's ACM portal to search through the catalog of APIs your company offers and their documentation.

Your portal may include news, events, tutorials, and posts on a developer blog.

Developers can use the forums on the portal to collaborate, share ideas, and discuss any issues they find.

ACM also integrates with the Salesforce Service Console to help consumer developers file support cases and to help API engineers resolve the cases.
