= Set Up the Data Bridge
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

The data bridge is the secure connection from Anypoint API Community Manager to your Anypoint Platform organization.

API Community Manager components and data objects use Anypoint Platform as their external data source.

== Create a Key Pair

This key pair will be created in Salesforce and used for communication between Salesforce and Anypoint.

. Click *Setup* > *Certificate and Key Management* > *Create Self-Signed Certificate*.
. Choose a *Label/Name* and remember the name you chose.
. Disable *Exportable Private Key*.
. Set *Key Size* to 2048 or larger.
. Click *Save*.
. Click *Download Certificate*.

The public key is saved on your local machine, and you will use it in the following steps.

== Create Connected App in Anypoint

. Click *Access Manager* > *Connected Apps* > *Create App*.
. Choose a name.
. Enable *App acts on behalf of a user*.
. In the section *Grant types* enable *JWT Bearer*.
. Copy the public key from the file downloaded in the previous steps and paste it into the public key text area.
. Set *Website URL* to `+https://login.salesforce.com+`.
. In the section *Redirect URIs* add `+http://localhost+`.
+
Connected apps require redirect URIs but this configuration does not use them.
. In the section *Who can use this application?* select *Members of this organization only*.
. In the section *Scopes* add *Background Access* and *Full Access*.
. Click *Save*.

You receive a client ID and a client secret. This configuration uses the certificate and does not use the client secret. Save the client ID so you can use it in the following steps.

== Prepare Identity Provider Data

If you already have Anypoint Identity Provider (IdP), get identity provider data from your current configuration:

. Click *Access Management* > *Identity Providers*.
. On *SAML 2.0* click *Edit*.
. Copy the issuer and the audience so you can use them in the following steps.

If you do not already have Anypoint Identity Provider, configure external identity in your Anypoint organization:

. In your connected app screen, click *Manage*.
. Make a note of the URIs under the *SAML Login Information* to use them in the Anypoint configuration in these steps.
. Click *Download metadata* and retrieve the public key in the `<ds:X509Certificate>` tag inside the XML file.
. Log in to your Anypoint organization.
. Navigate to *Access Management* -> *External Identity* -> *Identity Management* -> *SAML 2.0*.
. Set *Sign On URL* to *IdP-Initiated Login URL*.
. Set *Sign Off URL* to *Single Logout Endpoint*.
. Set *Issuer* to match the Salesforce account: `salesforce_org_domainname`.
. Set the *Public Key* to the public key extracted from the `<ds:X509Certificate>` tag in the metadata XML you downloaded.
. Set *Audience* to match the *Entity Id* you set in the Salesforce account.
. Select *Enable new non-SSO users*.
. Click *Save*.

== Configure Named Credential

. Click *Setup* > *Named Credentials*.
. Modify the named credential *anypoint_mulesoft*.
. Set *URL* to `+https://anypoint.mulesoft.com+`.
. Go to the *Authentication* section.
. Set *Identity Type* to *Per User*.
. Set *Authentication Protocol* to *JWT Token Exchange*.
. Set *Token Endpoint Url* to `+https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token+`.
. Set *Issuer* to the client ID of the connected app you saved previously.
. Set *Per User Subject* to the following formula.
+
Replace `IDP_ISSUER` with the issuer from your IdP configuration. Replace `IDP_AUDIENCE` with the audience from your IdP configuration.
+
`"{IDP_ISSUER}:{IDP_AUDIENCE}|" &  $User.Username & "|" & $User.FirstName & "|" & $User.LastName & "|" & $User.Email & "|[\"Community User\"]"`
. Set *Audiences* to `+https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token+`.
. Set *JWT Signing Certificate* to the certificate you downloaded when you created a key pair in the previous steps.
. In the *Callout Options* section, enable *Generate Authorization Header*.

== Modify External Data Source

. Click *Setup* > *External Data Source* > *Exchange*.
. Set *URL* to `callout:acm_pkg__{anypoint_mulesoft/odatabridge/odata.svc/`.
. Go to the *Authentication* section.
. Set *Identity* to *Anonymous*.
. Set *Authentication Protocol* to *No Authentication Protocol*.

== User Configuration

Give your user the *Organization Administrators* role:

. In your Anypoint Platform organization, click *Access Management* > *Users*.
. Select your user.
. Click *Role* > *Add role by name*.
. Add the role *Organization Administrators*.

Map community user to Anypoint role:

. In your Anypoint Platform organization, navigate to *Access Management* and click *Roles*.
. In *Exchange Viewers*, set a new External group called `Community User` and save it.
