= MuleSoft Government Cloud Data Control
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Your MuleSoft Government Cloud organization can restrict the data entities exposed to its Salesforce Experience Cloud API Community Manager instance.

Restrictions are defined on the Anypoint Platform organization management plane and applied at the data bridge level.

Before defining the entities and restrictions, get an authorization token from the Anypoint Platform identity services API endpoint `/accounts/login` by sending the username and password of a user with the Organization Administrator permission.

To define the restricted data entities and the operations allowed on each, use the token to make the API request to set a property in your Anypoint Platform organization.

Entities not listed in this configuration setting allow create, read, update, and delete operations.

Entities listed in this configuration setting allow only the listed operations, and all operations not present in the permissions array are blocked. Attempting a blocked operation returns an HTTP 403 error.

== Example Request

This example API request enables all operations on the `AnypointApplication` entity but only the read operation on the `AnypointCategory` entity:

----
curl --location --request PUT 'https://gov.anypoint.mulesoft.com/accounts/api/organizations/<ORG_ID>' \
--header 'Authorization: Bearer <YOUR_BEARER_KEY>' \
--header 'Content-Type: application/json' \
--data-raw '{ "properties": {
    "acm": {
        "entities": {
            "AnypointApplication": {
                "permissions": ["create", "read", "update", "delete"]
            },
            "AnypointCategory": {
                "permissions": ["read"]
            }
        }
    }
}}'
----

== Available Entities

* `AnypointApi`
* `AnypointApis`
* `AnypointApiCategory`
* `AnypointApiCategories`
* `AnypointApiFile`
* `AnypointApiGroupInstance`
* `AnypointApiGroupInstances`
* `AnypointApiGroupInstanceApiInstance`
* `AnypointApiGroupInstancesApiInstances`
* `AnypointApiGroupTier`
* `AnypointApiGroupTiers`
* `AnypointApiGroupTierLimit`
* `AnypointApiGroupTierLimits`
* `AnypointApiGroupVersion`
* `AnypointApiGroupVersions`
* `AnypointApiInstance`
* `AnypointApiInstances`
* `AnypointApiPage`
* `AnypointApiPages`
* `AnypointApiProduct`
* `AnypointApiProducts`
* `AnypointApiStat`
* `AnypointApiStats`
* `AnypointApiTier`
* `AnypointApiTiers`
* `AnypointApiTierLimit`
* `AnypointApiTierLimits`
* `AnypointApiVersion`
* `AnypointApiVersions`
* `AnypointApiVersionQuery`
* `AnypointApiVersionQueries`
* `AnypointApplication`
* `AnypointApplications`
* `AnypointApplicationOwner`
* `AnypointApplicationOwners`
* `AnypointAssets`
* `AnypointAssetCategories`
* `AnypointAssetVersions`
* `AnypointCategory`
* `AnypointCategories`
* `AnypointContract`
* `AnypointContracts`
* `AnypointContractOperation`
* `AnypointEnvironment`
* `AnypointEnvironments`
* `AnypointOrganization`
* `AnypointOrganizations`
* `AnypointResetClientOperation`
* `AnypointUser`
* `AnypointUsers`
* `CacheEvict`
* `ResetApplicationSecret`
* `RestoreApiContract`
* `RevokeApiContract`
