= Guided Setup
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

From the Anypoint API Community Manager control panel, open the Salesforce App Launcher and search for *API Community Manager Guided Setup*.

These steps require a configured identity provider. For more information about configuring an identity provider, see the xref:installation-prerequisites.adoc[installation prerequisites]. Using OpenID Connect as your identity provider requires using the xref:manual-setup.adoc[manual setup].

== Configure a Custom Subdomain

API Community Manager uses a custom subdomain to connect securely to your Anypoint organization.

This section of the guided setup helps you configure your subdomain, or displays the subdomain you have already configured.

== Connect with Your Anypoint Organization

To connect your API Community Manager instance to your Anypoint organization:

. Select your organization's Anypoint management plane, which may be the US control plane, the EU control plane, the MuleSoft Government Cloud control plane, or another control plane.
. Create a connected app in your Anypoint organization for Salesforce to use as a consumer system.
+
If your Anypoint account has the organization administrator role, the guided setup tool can create the connected app for you.
+
Otherwise, ask an organization administrator to create the connected app for you, or perform these steps:
+
.. Create a key pair in Salesforce for communication between Salesforce and Anypoint Platform:
... Click *Setup* > *Security* > *Certificate and Key Management* > *Create Self-Signed Certificate*.
... Set *Label/Name* to `Anypoint`.
... Disable *Exportable Private Key*.
... Set *Key Size* to 2048 or larger.
... Click *Save*.
... Click *Download Certificate* to save the public key on your local machine.
.. Click *Access Management* > *Connected Apps* > *Create App*.
.. Enter a name for the app.
.. Enable *App acts on behalf of a user*.
.. In the section *Grant types*, enable *JWT Bearer*.
.. Copy the public key from the downloaded file and paste it into the public key text area.
.. Verify that the public key certificate has this format:
+
----
-----BEGIN CERTIFICATE-----
PUBLIC KEY
-----END CERTIFICATE-----
----
.. Set *Website URL* to `+https://login.salesforce.com+`.
.. In the section *Redirect URIs*, add `+http://localhost+`, because connected apps require redirect URIs but this configuration does not use them.
.. In the section *Who can use this application?*, select *Members of this organization only*.
.. In the section *Scopes*, add *Background Access* and *Full Access*.
.. Click *Save*.
.. Copy the client ID.
.. Do not copy the client secret, because this configuration uses the certificate instead.
. Authenticate and authorize the connected app to access your Anypoint organization.
+
If your Anypoint account has the organization administrator role, provide your Anypoint Platform user and password, and the guided setup will create the app.
+
Otherwise, provide these app details:
+
.. Set *Client ID* to the client ID from the connected app you created.
.. In your Anypoint Platform organization, click *Access Management* > *Identity Providers* > *SAML 2.0* > *Edit* and copy the *IDP Issuer* string.
.. Set *IDP Issuer* to the *IDP Issuer* string.
.. In your Anypoint Platform organization, click *Access Management* > *Identity Providers* > *SAML 2.0* > *Edit* and copy the *Audience* string.
.. Set *Audience* to the *Audience* string.
.. Click *Connect* to authenticate and authorize the app to connect the API Community Manager organization with your Anypoint organization.

== User Configuration

Give your user the *Exchange Contributor* role:

. In your Anypoint Platform organization, click *Access Management* > *Users*.
. Select your user.
. Click *Role* > *Add role by name*.
. Add the role *Exchange Contributor*.

Map community user to Anypoint role:

. Ensure that you have Exchange Administrator permissions.
. In your Anypoint Platform organization, navigate to *Access Management* and click *Roles*.
. In *Exchange Viewers*, set a new external group called `Community User` and save it.
+
If you work with different business groups, you must create a new external group for each business group in your organization.

== Next Steps

After the connection with your Anypoint organization is established, click *Continue* to open the API Community Manager diagnostics tool, review your installation, and if necessary, update the guest user and member user permissions. After the installation and permissions are verified, create your first community.

== See Also

* xref:diagnostics.adoc[Diagnostics]
* xref:create-community.adoc[Create a Community]
