= API Community Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

API Community Manager (ACM) enables your company to build APIs, catalog them with Anypoint Exchange, and make them available to software developers inside and outside of your company.

ACM relies on MuleSoft's Anypoint Exchange as the single source of truth about published APIs, and Salesforce Community Cloud's ability to add customization, branding, and marketing information to serve unique content to different audiences.

ACM provides an array of features, such as chat, forums, and support integration. This way the experience of developers using your company's APIs is as rich and polished as the experience of customers using your company's products.

ACM also introduces API products. An API product is a group of APIs with marketing context. For example, a payments product might include three APIs for Apple pay, Android pay, and wire transfers.

== The ACM Consumer Developer Experience

Many companies use Salesforce Community Cloud to build branded and customized online portals to offer their products to their customers.

In the same way, your company can use API Community Manager to build branded and customized online portals to offer its APIs to the internal and external software developers who write code that uses and consumes those APIs.

These consumer developers will arrive at your company's site, which may include news, events, tutorials, and posts on a developer blog. Developers can search through a catalog of available APIs and documentation.

Developers can use the forums on the portal to collaborate, share ideas, and discuss any issues they find.

ACM also integrates with the Salesforce Service Console to help consumer developers file support cases and to help API engineers resolve the cases.

== See Also

// * xref:release-notes::acm/api-community-manager-release-notes.adoc[API Community Manager Release Notes]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
