= API Community Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

API Community Manager (ACM) enables your company to build APIs, catalog them with Anypoint Exchange, and make them available to software developers inside and outside of your company.

ACM relies on MuleSoft's Anypoint Exchange as the single source of truth about published APIs, and Salesforce Community Cloud's ability to add customization, branding, and marketing information to serve unique content to different audiences.

ACM provides an array of features, such as chat, forums, and support integration. This enables your company to treat its APIs as product, and treat the developers using those APIs as customers.

ACM also introduces API products. An API product is a group of APIs with marketing context. For example, a payments product might include three APIs for Apple pay, Android pay, and wire transfers.

== See Also

// * xref:release-notes::acm/api-community-manager-release-notes.adoc[API Community Manager Release Notes]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
