= API Community Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

With API Community Manager (ACM), you can build and operate a community for developers and partners, both 
inside and outside of your organization, who write applications that use your APIs.

ACM is powered by *Salesforce Community Cloud*, and provides customization, branding, marketing, and 
engagement capabilities to serve the different needs of your developer audiences. APIs stored in 
MuleSoft's Anypoint Exchange can be surfaced in ACM.

See these useful resources to get up-to-speed with Salesforce Community Cloud:

* https://help.salesforce.com/articleView?id=networks_resources.htm&type=5[Community Cloud Product Documentation, role=external, window=blank]
* https://trailhead.salesforce.com/en/content/learn/trails/communities[Community Cloud Trailhead, role=external, window=blank]

== What is an API Community?

To drive developer adoption of your APIs, you must help them discover and learn how to use your APIs effectively, 
and provide a personalized, branded experience to motivate them to work with you. You must also engage with these 
developers during every step of their journey to ensure their success. ACM provides this personalized, connected 
experience for your developers when interacting with your APIs - APIs that you've designed, catalogued, and now 
manage in the Anypoint Platform. 

As a community administrator, you use ACM to create a visually compelling digital experience that is consistent 
with your organization's brand identity. Your community showcases APIs that you select directly from 
Anypoint Exchange, plus other relevant content and self-service resources to inspire and help the developers 
you want to reach.

== A Connected and Personalized Digital Experience for Your Consumer Developers

A consumer developer accessing your API community finds news, events, tutorials, developer blog posts, and the 
APIs you selected from Anypoint Exchange, in a branded, customized experience. This includes content 
created by your marketing and business development teams to help your audiences understand the impact of your APIs.

The community also delivers technical API documentation so that developers can explore specific API features and 
learn how to use the APIs. This information is made available directly from the API designs in Anypoint Platform. 
Each API has a console in which developers can try out the API. 

Developers request access to an API for new or existing applications, and your organization approves these 
requests with the same process used in API Manager. Developers manage their applications, manage 
application credentials, including API keys and secrets, and get insights on their applications' performance 
as their applications use your APIs. 

Developers use the forums to engage with your organization and other members of the community. In the forums, 
they can post questions and answers, share ideas, and discuss issues they find. 

Other ACM features enable your organization to engage with partners and ensure they are supported throughout their journey.

== Building Your API Community

Personalize your community look and feel, branding, and site-structure with the Community Builder, a 
drag-and-drop editor that allows you to create and customize the experience down to the finest level of detail. 
The Community Builder makes it easy to publish a tailored experience using pre-existing components, simple clicks, and code.

== Manage the Anypoint Exchange APIs and Versions That are Presented to Your Developers  

Pre-built dashboards show you how the content and assets in your community are being used, so you understand 
the activity in your ecosystem. These out-of-the-box dashboards leverage more than ten years of Salesforce experience 
to reflect best practices in community engagement.

With ACM, you have a digital experience platform to build and nurture your API ecosystem, 
increase developer engagement, and personalize experiences with clicks and code.

== See Also

// * xref:release-notes::acm/api-community-manager-release-notes.adoc[API Community Manager Release Notes]
* https://forums.mulesoft.com[MuleSoft Forum, role=external, window=blank]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles, role=external, window=blank]
