= API Community Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

With Anypoint API Community Manager, you can build and operate communities around your APIs for developers and partners, both inside and outside of your organization, who write applications that use your APIs.

API Community Manager is powered by *https://www.salesforce.com/products/community-cloud/overview/[Salesforce Community Cloud, role=external, window=blank]* and provides customization, branding, marketing, and engagement capabilities to serve the different needs of your developer audiences. APIs cataloged in https://docs.mulesoft.com/exchange/[Anypoint Exchange] can be surfaced in API Community Manager for developers to discover them and use them to manage client applications, API access credentials, and consumption metrics.

See these useful resources to get up to speed with the capabilities of Salesforce Community Cloud:

* https://help.salesforce.com/articleView?id=networks_resources.htm&type=5[Community Cloud Product Documentation, role=external, window=blank]
* https://trailhead.salesforce.com/en/content/learn/trails/communities[Community Cloud Trailhead, role=external, window=blank]

== What Is an API Community?

To drive developer adoption of your APIs, you must help them discover and learn how to use your APIs effectively, and provide a personalized, branded experience to motivate them to work with you. You must also engage with these developers during every step of their journey to ensure their success. API Community Manager enables you to create this personalized, connected experience for your developers so they can interact with your APIs: APIs designed, cataloged, and managed in Anypoint Platform.

As a community administrator, you use API Community Manager to create a visually compelling digital experience that is consistent with your organization's brand identity. Your community showcases APIs that you select directly from https://docs.mulesoft.com/exchange/[Anypoint Exchange], plus other relevant content and self-service resources to inspire and help the developers you want to reach.

== A Connected and Personalized Digital Experience for Your Consumer Developers

A consumer developer accessing your API community finds news, events, tutorials, developer blog posts, and both business and technical information about your APIs, in a branded, customized experience.

Information in your community includes content created by your marketing and business development teams to help your audiences understand the value proposition of your APIs, in addition to the technical API documentation and self-service API console that helps developers explore API features and learn how to use them. The API technical information is made available directly from the API designs in Anypoint Platform.

Consumer developers can request access to your API for new or existing client applications, following the regular governance model of the API lifecycle provided by Anypoint Platform and https://docs.mulesoft.com/api-manager/2.x/latest-overview-concept[API Manager]. Developers can manage their client applications, their access credentials (API keys and secrets), and get insights on their applications' performance as their applications use your APIs.

Developers use discussion forums to engage with your organization and other members of the community, by posting questions and answers, sharing ideas, and discussing issues they find.

Other API Community Manager features enable your organization to engage with partners and ensure that they are supported throughout their journey.

== Building Your API Community

Personalize your community look and feel, branding, and site structure by using  https://help.salesforce.com/articleView?id=community_designer_overview.htm&type=5[Community Builder, role=external, window=blank], a drag-and-drop editor that enables you to create and customize the user experience at every level of detail. Community Builder makes it easy to create a tailored experience using pre-existing Lightning components and simple clicks, or using the full flexibility of HTML and CSS for precise pixel-perfect experiences.

== Understand How Your Developers Engage in Your Community

https://help.salesforce.com/articleView?id=networks_appexchange_overview_dashboard_and_reports.htm&type=5[Pre-built dashboards, role=external, window=blank] show you how the content and assets in your community are being used, so you understand the activity in your ecosystem. These out-of-the-box dashboards leverage more than ten years of Salesforce experience to reflect best practices in community engagement.

== See Also

* xref:release-notes::api-community-manager/api-community-manager-release-notes.adoc[API Community Manager Release Notes]
* https://forums.mulesoft.com[MuleSoft Forum, role=external, window=blank]
* https://help.mulesoft.com/s/knowledge[Knowledge Base Articles, role=external, window=blank]
