= Install and Configure
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/
:page-aliases: install-configure.adoc, configure-acm.adoc

Anypoint API Community Manager is composed of a Salesforce organization with Experience Cloud and a managed package that is installed in this organization. The managed package contains the components and data objects that interact with your Anypoint Platform organization.

An instance of API Community Manager connects to only one Anypoint Platform organization. The Anypoint user can connect to one or more instances of API Community Manager, possibly including sandbox instances and instances in other Salesforce organizations.

The API Community Manager package is installed in a Salesforce organization that is independent of any other Salesforce organizations that your company might already have, so that the API community data is isolated from your company operational data, such as ERP or CRM data.

The Salesforce organization with Experience Cloud is provisioned through and included in the Anypoint API Community Manager license from MuleSoft. You don't need to procure this Salesforce organization separately, and you cannot reuse existing Salesforce licenses for API Community Manager. Find more information about API Community Manager licenses in the xref:licensing-overview.adoc[Licensing Overview] section.

NOTE: Installing, updating, or configuring API Community Manager must be done by a user account with the *System Administrator* profile in the API Community Manager Salesforce organization.

NOTE: If your Anypoint Platform organization is https://docs.mulesoft.com/eu-control-plane/platform-access-eu[hosted in the EU region, role=external, window=_blank] you must replace all occurrences of the `anypoint.mulesoft.com` domain with `eu1.anypoint.mulesoft.com` in all the steps in this section.

The following sections guide you through installing and configuring API Community Manager:

* xref:installation-prerequisites.adoc[Installation Prerequisites]
* xref:install-acm.adoc[Install API Community Manager Package]
* xref:guided-setup.adoc[Guided Setup]
* xref:manual-setup.adoc[Manual Setup]
* xref:cache.adoc[Configure the Platform Cache]
* xref:create-community.adoc[Create a Community]
* xref:install-validate.adoc[Verify the Installation]
* xref:search-cms.adoc[Optionally Configure Search in CMS Content]
* xref:branded-emails.adoc[Optionally Configure Branded Emails]
* xref:govcloud-data-control.adoc[MuleSoft Government Cloud Data Control]
