= Installation Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

To install Anypoint API Community Manager you will need:

. An Anypoint admin user account.
. A Salesforce API Community Manager organization admin user with a role.
+
To update your user role and permissions:

.. Log in to your Salesforce organization.
.. In *Setup*, search for *Users* using the *Quick Find* box and click *Users*.
.. Locate your username and click *Edit*.
.. Set the *Role* for your account.
+
This can be any role from the list, but cannot be none.
+
If you don't see any roles in the list, refer to the Salesforce knowledge article https://help.salesforce.com/articleView?language=en_US&type=1&mode=1&id=000322715[Add roles to the role hierarchy, role=external, window=_blank] for instructions to create a role in your organization.

.. Select *Salesforce CRM Content User*.
.. Click *Save*.
. The Anypoint API Community Manager entitlement for your Anypoint organization.
+
To check the entitlement:

.. Log in to your Anypoint Platform organization.
.. Navigate in your browser to `+https://anypoint.mulesoft.com/accounts/api/profile+`.
.. Verify that under the *Entitlements* property, the `apiCommunityManager` value is `true`.

After you have confirmed that you have these prerequisites, continue to the installation steps.
