= Install API Community Manager Package
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

NOTE: Installing, updating, or configuring Anypoint API Community Manager must be done by a user account with the *System Administrator* profile in the API Community Manager Salesforce organization.

To perform a new install of the API Community Manager package in your API Community Manager Salesforce Organization, perform the following steps. To update an existing API Community Manager installation, refer to xref:update-acm.adoc[Update API Community Manager].

. In your browser, navigate to the package installation link provided by your MuleSoft representative.
. Select *Install for Admin users only*.
. Select *I acknowledge that I'm installing a Non-Salesforce Application that is not authorized for distribution as part of Salesforce's AppExchange Partner Program*.
. Select *Install*.
. On the *Approve Third-Party Access* page, select the *Yes, grant access to these third-party web sites* check box.
. Select *Continue*.
. When installation completes, select *Done*.


NOTE: If you see a message indicating that the installation process is taking a long time to install, you will
receive an email when the installation completes.

You can verify that API Community Manager installation is successful by reviewing the *Installed Packages* information
in *Setup*.
