= Installation Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

API Community Manager (ACM) is composed of a Salesforce organization with Community Cloud and a managed package that is installed in this organization. The managed package contains the components and data objects that interact with your Anypoint Platform organization.

The ACM package is installed in an *independent* Salesforce organization from any other Salesforce organizations your company may already have, so that the API community data is isolated from your company operational data, such as ERP or CRM data.

The Salesforce organization with Community Cloud is provisioned through and included in the MuleSoft ACM license. You don't need to procure this Salesforce organization separately, and you cannot reuse existing Salesforce licenses for ACM. Find more information about ACM licenses in the xref:licensing-overview.adoc[Licensing Overview] section.

Installing, updating or configuring ACM must be done by a user account with the *System Administrator* profile in the ACM Salesforce organization.

To install and configure the ACM managed package, use the following preparation steps in this Salesforce organization.

== Set Up and Register a Domain

// Is this the right site for an inline link: https://help.salesforce.com/articleView?id=sites_creating_subdomain.htm&type=5?

. Log in into your ACM https://login.salesforce.com/[Salesforce Organization, role=external, window=blank].
. Go to *Salesforce Set-up* by selecting the gear icon and selecting *Set-up*.
. Search for *My Domain* using the *Quick Find* box and then select *My Domain*.
. Enter a name for *My Domain*. The name can include up to 34 letters, numbers, and hyphens.
. Select *Check Availability*. If the name is already taken, choose a different one.
. Select *Register Domain*. You will receive an email when your subdomain name is ready for testing. This process
can take a few minutes.
. Follow the instructions in the email.

== Enable Communities Inside Your Organization

Follow the steps in
https://help.salesforce.com/articleView?id=networks_enable.htm&type=5[Enable Salesforce Communities, role=external, window=blank]
to enable communities inside your Salesforce organization.

== Deploy Your Domain

. Search for *My Domain* using the *Quick Find* box and then select *My Domain*.
. Select *Deploy to Users*.
