= Installation Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

To install Anypoint API Community Manager you will need:

. An Anypoint admin user account.
. A Salesforce API Community Manager organization admin user with a role.
+
To update your user role and permissions:

.. Log in to your Salesforce organization.
.. In *Setup*, search for *Users* using the *Quick Find* box and click *Users*.
.. Locate your username and click *Edit*.
.. Set the *Role* for your account.
+
This can be any role from the list, but cannot be none.
+
If you don't see any roles in the list, refer to the Salesforce knowledge article https://help.salesforce.com/articleView?language=en_US&type=1&mode=1&id=000322715[Add roles to the role hierarchy, role=external, window=_blank] for instructions to create a role in your organization.

.. Select *Salesforce CRM Content User*.
.. Click *Save*.
. The Anypoint API Community Manager entitlement for your Anypoint organization.
+
To check the entitlement:

.. Log in to your Anypoint Platform organization.
.. Navigate in your browser to `+https://anypoint.mulesoft.com/accounts/api/profile+`.
.. Verify that under the *Entitlements* property, the `apiCommunityManager` value is `true`.
. Identity provider data.

== Prepare Identity Provider Data

=== If You Already Have Anypoint Identity Provider

If you already have Anypoint Identity Provider, get identity provider data from your current configuration:

. Click *Access Management* > *Identity Providers*.
. On *SAML 2.0* click *Edit*.
. Copy the issuer and the audience so you can use them in the installation.

=== If You Do Not Already Have Anypoint Identity Provider

If you do not already have Anypoint Identity Provider (IdP), configure Salesforce as a SAML IdP:

. In *Setup*, search for *App Manager* using the *Quick Find* box and click *App Manager*.
. Click *New Connected App* in the top right.
. Provide this information in the *Basic Information* section.
.. *Connected App Name*: `Anypoint`.
.. *Contact Email*: Enter your email address.
. Provide this information in the *Web App Settings* section.
.. Provide the *Start URL*: `+https://anypoint.mulesoft.com/accounts/login/<your_anypoint_domain_name>+` or the location
where you want users to be sent in Anypoint Platform.
+
You can find your Anypoint organization domain name by clicking *Access Management* > *Organization* and then selecting the root organization.
.. Select *Enable SAML*.
.. Provide any string as *Entity Id*. This is also the *Audience* configuration in Anypoint Platform.
.. Provide `+https://anypoint.mulesoft.com/accounts/login/receive-id+` in the *ACS URL*. SAML assertions are sent to this ACS URL.
.. Select *Enable Single Logout*.
.. Provide *Single Logout URL*: `+https://anypoint.mulesoft.com/accounts/logout/receive-id+`.
.. Set *Single Logout Binding* to *HTTP Post*.
.. Set *Subject Type* to *Username*.
.. Set *Name ID* Format to *unspecified nameID format*.
.. Set *Issuer* to *salesforce_org_domainname* (such as `+https://[YourOrgDomain].my.salesforce.com+`).
.. Set *IdP Certificate* to *Default IdP Certificate*.
.. Click *Save*.

Configure external identity in your Anypoint organization:

. In the Salesforce organization, click *Setup*, use the *Quick Find* box to search for *Identity Provider*, and click *Identity Provider*.
. Click *Enable Identity Provider*.
. Save.
. Use the *Quick Find* box to search for *App Manager*, choose the app named *Anypoint*, and in the last column of the table, click the arrow and click *Manage*.
. Make a note of the URIs under the *SAML Login Information* to use them in the Anypoint configuration in these steps.
. Click *Download metadata* and retrieve the public key in the `<ds:X509Certificate>` tag inside the XML file.
. Log in to your Anypoint organization.
. Navigate to *Access Management* > *Identity Providers* > *SAML 2.0*.
. Set *Sign On URL* to *IdP-Initiated Login URL*.
. Set *Sign Off URL* to *Single Logout Endpoint*.
. Set *Issuer* to match the Salesforce account: `salesforce_org_domainname`.
. Set the *Public Key* to the public key extracted from the `<ds:X509Certificate>` tag in the metadata XML you downloaded.
. Set *Audience* to match the *Entity Id* you set in the Salesforce account.
. Select *Enable new non-SSO users*.
. Click *Save*.

== Next Steps

After you have confirmed that you have these prerequisites, continue to the installation steps.
