= Installation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

TOC Relative links - TBD
Installation
- Organization Installation Requirements

Installation Requirements
- Installing API Community Manager 
- Update API Community Manager
- Create a Community
- API Community Manager Components
- Publish API Community Manager???
- Configure Guest User Access
- Configure Registered Users
- Configure API Community Manager
- Set permissions for Unauthenticated users
- How to enable external users to register in your Community
- Define moderation rules for forums
- How to setup an Approval Process for new Community Users

Customize Login and Registration Pages
Troubleshooting
Reference: Auth Provider details


== Installation Requirements

API Community Manager is installed in an *independent* Salesforce organization so that the API community is isolated 
from customer operational data in their Salesforce instance (ERP, CRM, etc).

API Community Manager requires an ACM licenses. You cannot reuse an existing Salesforce license for ACM.

. Set up and register a domain:

.. Log in into your https://login.salesforce.com/[Salesforce Organization].
.. Search for *My Domain* using the *Quick Find* box and then select *My Domain*.
.. Enter a name for *My Domain*. The name can include up to 34 letters, numbers, and hyphens.
.. Select *Check Availability*. If the name is already taken, choose a different one.
.. Select *Register Domain*. You will receive an email when your subdomain name is ready for testing. This process 
can take a few minutes. 
.. Follow the instructions in the email.

. Enable Communities inside your organization (logged in with the new user created):

.. Enter `Communities Settings` in the *Quick Find* box and then select *Communities Settings*.
.. Select *Enable Communities*.
.. Select a domain name for your communities, and select *Check Availability*. If the name is already taken, 
choose a different one.
.. Select *Save*.

. Make your domain available to your users:

.. Search for *My Domain* using the *Quick Find* box and then select *My Domain*.
.. Click *Deploy to Users*.

If you are using another type of Salesforce Organization, you need the following features available:???

* Salesforce identity

== Install API Community Manager

. Navigate to the https://login.salesforce.com/packaging/installPackage.apexp?p0=04t4P000002ErbpQAC[Package Installation Link]. 

. Select the appropriate release to install for your organization.
. Select *Install*.
. On the *Approve Third-Party Access* page, select the *Yes, grant access to these third-party web sites* check box.
. Select *Continue*.
. When installation completes, select *Done*. 

NOTE: If you see a message indicating that the installation process is taking a long time to install, you will 
receive an email when the installation completes.

You can verify that API Community Manager installation completed by reviewing the *Installed Packages* information 
in *Setup*.

=== Authenticate the *External Data Source*
.. Search for *External Data Source* in the *Quick Find* box and then select *External Data Sources*. 
This external data source specifies how to access to Mulesoft Anypoint system.
.. Select *Exchange* and then select *Edit*.
.. Update *Identity Type* to *Named Principal*.
.. Update *Authentication Protocol* to *OAuth 2.0*.
.. Update *Authentication Provider* to *Anypoint*.
.. Select *Save*. The *Anypoint Login* page is shown.
.. Log in to the Anypoint Platform.
.. Search for *External Data Source* in the *Quick Find* box and then select *External Data Sources*. 
The *External Data Sources* information for Exchange indicates that the *Authentication Status* is *Authenticated*. 
If you have problems with this configuration, check the Auth. Provider callback endpoint and your domain 
configuration. How????
.. Search for *Named Credentials* in the *Quick Find* box and then select *Named Credentials*.
.. Select *Edit*.
.. In the *Authentication* section, enter the Anypoint username and password in the *Username* and 
*Password* fields, respectively.
.. Select *Save*.

=== Update API Community Manager

To update to a later version of API Community Manager:

. Navigate to the https://login.salesforce.com/packaging/installPackage.apexp?p0=04t4P000002ErbpQAC[Package Installation Link].
. Select the appropriate release for your organization.
. Select *Upgrade*.
. When the upgrade is complete, select *Done*.

If you have a highly customized ACM:

. Install *package updates* to ACM components as they become available.
. A package update is a link that a salesforce admin opens after logging in to their salesforce instance. Opening the 
link updates all components with the new features.
- Package updates are backwards-compatible, so that installing a package does not 
break existing functionality - except special cases that will be communicated.

=== Create a Community

. If you are not familiar with Communities, refer to the https://help.salesforce.com/articleView?id=networks_resources.htm&type=5[Salesforce Community Overview].
. Navigate to *Setup*.
. In the *Quick Find* box, enter *All Communities* and then select *All Communities*.
. Select *New Community*. All communities templates are listed. 
. Choose *API Community Manager Template*.
. On the *API Community Manager* page, select *Get Started*.
. Enter a *Name* and a *URL*. 
. Select *Create*.
. After the new community is created, select *Builder* to modify the community appearance and components if needed. 
. Navigate to *Administration* and select *Activate Community*.


=== Add API Community Manager Components

. Navigate to the Community Builder to view the API Community Components. Drag components to your community pages as needed.

=== Publish Your Community

. In the Community Builder, select *Publish*. 
. In the *Publish Your Community* page, select *Publish*.
. You will receive an email with the following information:
`Congratulations! User was published successfully and is now live on the following domain(s):
https://exampledomain-developer-edition.na91.force.com/mydomain/s`


=== Configure Guest User Access
After the community is created, you must create the community profile and add permissions.

. Create the profile to be assigned to new Community Users.

.. Navigate to *Setup*.
.. In the *Quick Find* box, enter *Users*.
.. Select *Profiles*.
.. In the *Profiles* page, select *Clone* next to the *Customer Community User* profile.
.. In the *Profiles* page, enter ‘ACM [ Community Name ] User’ for *Profile Name*. 
.. Select *Save*.
. Change permissions for *External Objects* and *Custom Objects*.
.. Navigate to *Field-Level Security*.
.. In the *Custom Field-Level Security* section, repeat the following step for the *AnypointApiVersions*,
*AnypointApplications*,
*AnypointContracts*,
*AnypointApiInstances*, and
*CommunityApi items*:
.. Select *View* and then *Edit* . ????which fields need to be updated?????

=== Create a Public Group

. Navigate to *Setup -> Users -> Public Groups*.
. Select *Create New View*.
. Enter `[Community Name] Public Group` for *Label*.
. In the *Search* field, enter *Users*.
. Enter `User: [Community Name] Site Guest User` in the *Selected Members* column.
. Select *Save*.

=== Create *Sharing Settings*

These settings use the Public Group that you previously created.

. Navigate to *Setup -> Security -> Sharing Settings*.
. Scroll to and select *CommunityApi Sharing Rules*.
. Select *New*.
. In the *Rule Name* section, update *Label* with ‘[Community Name] Guest’.
. In the *Select your rule type* section, select ‘Based on criteria’.
. In the *Select which records to be shared* section, add the following criteria:

.. *Field*: `Community Name` *Operator*: `equals` *Value*: ‘[Community Name]’
.. *Field*: `Visibility` *Operator*: `equals` *Value*: `Public`
. In *Select the users to share with*: enter *Share with*: `Public Groups` and `[Community Name] Public Group`.
. In *Select the level of access for the users*, select *Read Only*.
. Select Save.
. Switch to salesforce classic (how????).
. Select the plus (+) button.
. In *View*, select *Content* and then select *Libraries*.
. In the *Manage Libraries* section, select *Asset Library*.
. In the *Members* section, select *Add Members*.
. In the *Edit Library Membership Wizard*, select ‘Public Groups’ from the *Search* drop-down and add the 
public group previously created.
. Assign the *Viewer* Permission and select *Save*.


=== Configure Registered Users

. Navigate to *Setup* -> *Communities* -> *Communities Settings*.
. Scroll to *Sharing Sets* and select *New*.
. In the *Sharing Set Edit* section, update *Label* with ‘[Community Name] Sharing Set’ . Select *Save*.
. Select *ACM [Community name] User* from *Available Profiles* and add it to *Selected Profiles*.
. Select *CommunityApi* from *Available Objects* and add it to *Selected Objects*.
. In the *Action* column, select *Set Up*.
. Enter the information required in the *Access Mapping for CommunityApi* page. More info needed????


=== Configure API Community Manager
You must select the APIs to show in your Community.

. Select *API Community Manager App* from the *App Launcher*. The App Launcher icon is the first icon in the 
main navigation bar.

==== Give permissions to ACM Community Manager

If you cannot view ACM Community Manager content in the *Lightning Experience App Manager*, you must 
add the *ACM Administrator* tab from the App Manager in *Setup*:

. In *Setup*, search for App Manager in the *Quick Find* box and then select *API Community Manager* and edit it. 
. Navigate to *Navigation Items*, highlight *ACM Administrator*, and move it to the *Selected Items* column. Select *Save*.
. Log out and log back in to your Salesforce organization. 
. In the *ACM Administrator* tab, select *Manage APIs*. 
. Select the APIs you want to show in the Community portal using *Add to Community*. 
. As needed, change the description, icon, visibility and the marketing page of the APIs with the *Edit* button 
in the *Community* section.

=== Set permissions for Unauthenticated Users

. In the Community Builder, navigate to *Settings* -> *General* and select the *Public can access the community* check box.
. Navigate to *Settings* -> *SEO* and select *Guest User Profile*. Make the necessary changes.
. Navigate *Settings > General* and select *Guest User Profile*. 
. Select *Edit*.
. Enable *Read*, *Create*, *Edit*, and *Delete* permissions to the external objects listed in the 
*External Object Permissions* section.
. Select *Save*.
. Change the permissions for the following objects in the *Custom Field-Level Security* section:
*AnypointApiInstances*, *AnypointApiTiers*, *AnypointApiVersions*, *AnypointApplications*, 
*AnypointContracts*, and *CommunityApis*. Which settings??????? Do we need these screen shots???

=== Enable external users to register in your community
==== Assign the Profile to new Community Members

. Navigate to *Community Administration* > *Members*.
. Select *All* from the Search drop-down.
. Add *ACM [Community Name] User* to *Selected Profiles*.
. Select *Save*.

==== Create the Account for your community

. Navigate to *App Launcher -> Accounts*.
. Enter `ACM Registered Users` in *Account Name*.
. Select *Save*.

==== Configure your Login and Registration Page

. Navigate to *Community Administration > Login & Registration*.
. As needed, update the *Login Icon* information in *Branding Options*.
. On the *Registration Page Configuration* page:

.. Select *Allow external users to self-register*. 
.. Select *Community Builder Page* for *Registration Page Type* and select *Register*.
.. Select *ACM Registered Users* in *Profile*.
.. Select *ACM [ Community Name ] Account* in *Account*.
.. Select *Save*.

==== Ensure that the Portal Account Owner has a role set.

. Navigate to *Setup -> Users* and select your username.
. Set the appropriate *Role*.
. Select *Save*.

==== Add Self Register custom component to Register page

The self-register component allows your users to self-register in your community.

NOTE: Follow these steps only if you created a Community NOT using the ACM Template. Self Register custom 
component is automatically added to the Register page if you created a Community using the ACM Template.

. In the Community Builder, navigate to the *Register* page.
. Remove the standard *Self Registration* component by selecting the delete 
icon next to it.
. Navigate to *Components*, search for *Self Register* and add it to the page.????More info needed????
		

== Define moderation rules for forums

. Navigate to your Community Workspace.
. In the main navigation bar, select *Moderation -> Rules*.
. Create a rule. At a minimum, enter information for the *Name* and *Unique Name* fields in the *Details* section. 

IMPORTANT: Verify the *Activate Rule* check box is active and save the changes. 
. Enter information for all fields in the *Rule Conditions* section.

== Set up an Approval Process for new Community Users
Set up an approval process for self-registered users so that the system requires admin approval before creating a new user.

. Search for `Approval Processes` in the *Quick Find* box and then select *Approval Processes*.
. Select *Self Register User Request* in the *Manage Approval Processes For:* drop-down.
. Select *Use Standard Setup Wizard* in the *Create New Approval Process* drop-down.
. In the wizard, enter the following information:

.. Name and Description

*** *Process Name*: `Approve Registration`.
*** *Description*: Enter informatio that applies to your process.

.. Entry Criteria

*** *Field*: `SelfRegisterUserRequest: Approved`.
*** *Operator*: `equals`
*** *Value*: `False`.

.. *Self Register User Requests*: leave as default values
Make sure that *Record Editability Properties* shows *Administrators ONLY can edit records during the 
approval process* selected.

.. *Self Register User Requests*:
Make sure that *Approval Assignment Email Template* is set to  *Registration Request*. (select ACM folder 
on lookup window????).

.. Enter *Select Fields to Display on Approval Page Layout* information

*** Add `Self Register User Request Name` and `Owner` to *Selected Fields*:
*** Select *Display approval history information in addition to the fields selected above.* check box.

.. *Specify Initial Submitters*:

*** Add *Self Register User Request Owner* to *Allowed Submitters* column.


== Create an Approval Step
After you create the Approval Process:

* If you are prompted to add an Approval Step:

. Select *Yes, I'd like to create an approval step now*.
. Select *Go!*.

* If you are not prompted to add an Approval step:

. Search for *Approval Processes* in the *Quick Find* box. 
. Select *Approve Registration* (the approval that you created).
. In the *Approval Steps* section, select *New Approval Step*.

Continue with the following steps:

. In the *Step 1: Enter Name and Description* page:

.. Enter `Step 1` in *Name*.
.. Select *Next*.

. In the *Step 2: Specify Step Criteria* page, select *Next*.
. In the *Step 3 - Select Assigned Approver* page:

.. Select *Let the submitter choose the approver manually*.
. Select *Save*.

== Create a Final Approval Action

. On the *Self Register User Request: Approve Registration* page, navigate to *Final Approval Actions* and select *Add New*.
. Select *Field Update*.
. In the *Field Update Edit* section, enter the following values:

** *Name*: `Create User`
** *Field to update*: `Approved`
** *Re-evaluate Workflow Rules after Field Change*: Select the check box.
** **Checkbox Options*: `True`.
 . Select *Save*.


== Activate your Approval Process

. On the *Approve Registration* page, select *Activate* and confirm.
. In the Community Builder, navigate to the *Register* page, remove the default register component, and 
select ACM *Self Register*.
. Verify the Approved Registration and set *Approver Id*.

.. Navigate to Salesforce Setup.
.. Search for `Users` in the *Quick Find* box and then select *Users*.
.. Select the full name of the user who you want to be the approver.
.. The ID is contained in the URL of the User detail page you are currently viewing. In the following screen shot, 
the unique ID is 2F0052D000001QpG1. Remove the first 2 characters, in this case *2F*, and paste the remaining 
information in the *Approver Id* field. screen shot????

== Customize *Login* and *Registration* pages.

To change the background image and Company Logo displayed on Login and Register page, follow these steps:

. Navigate to *Community Builder*.
. Select *Register* or *Login Page* so you can see changes immediately.
. Select the *Theme* icon in the sidebar.
. If desired, Uupload a Company Logo.
. If desired, upload a Background Image.


== Troubleshooting

. Invalid Page
When the community is a public one, you must change the permissions in the Guest User Profile, and add read checks to the external objects.


== Further Reading

Auth provider details
Provider Type: Open ID Connect
Name: Anypoint
URL Suffix: Anypoint
Consumer Key: 9c4bc622-03d8-45de-a8f4-12b75f6dcb66
Consumer Secret: b2956605d9DD40F7a456507302A4E76a
Authorize Endpoint URL: https://anypoint.mulesoft.com/accounts/oauth2/authorize
Token Endpoint URL: https://anypoint.mulesoft.com/accounts/oauth2/token
...
Default Scopes: refresh_token


