= Licensing Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Anypoint API Community Manager licenses are procured and provisioned by MuleSoft. A standard API Community Manager license consists of a _Salesforce Customer Community Plus Login License Unlimited Edition_. It is based on the number of member logins per month, and includes as a base:

. Up to 100 communities
. Five (5) admin users (community administrators or operators)
. Connectivity to one (1) Anypoint Platform top-level organization
. Up to 10,000 member accounts across all communities
. Salesforce Standard Objects, Features, Capability, and Custom Objects in Customer Community Plus 
. 1Mb storage per user for all Communities
. 10Mb storage for organization and session caches
. 1MM page views per month across all Communities
. 40Gb network bandwidth in production for all communities and 1Gb network bandwidth for all sandboxes
. 100 Developer sandboxes, 5 Developer Pro sandboxes, 1 Partial Copy sandbox, 1 Full Copy sandbox
. 10 Custom Objects
. 10 API Calls per day to the Salesforce Community


Community login-based license is calculated by the number of *daily unique logins*: login actions that different members perform daily in your communities during a month. Members associated with your license consume one login each day they log into any of your communities. Logging in multiple times during the same day only consumes one login. Once logged in, switching between communities doesn’t consume extra logins.

Forecasting the adequate number of daily unique logins is critical to ensure that you have enough licenses to satisfy the demand your community will generate. Your MuleSoft account team will assist you in this analysis as part of the capacity planning and community design process before you roll out your community.

You can find more information about *Salesforce Customer Community Plus Login License Unlimited Edition* in the Salesforce Community Cloud documentation page https://help.salesforce.com/articleView?id=users_license_types_communities.htm&type=5[Communities User Licenses, role=external, window=blank].

NOTE: Additional capacity can be provisioned to your org if required. Please reach out to your MuleSoft representative for more information. 
