= Manage Users
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Consumer developers self-register for access to your API Community. You can then approve user registrations to give them access to the restricted sections of your community. 

== User Registration and Activation

When consumer developers browse your community as unregistered users (guests), they can view only limited information.

Consumer developers follow these steps to self-register:  

. Navigate to the community to which they want access.
. Select *Log in*.
. Select *Not a member?*
. Enter their community username and password. 
. Select *REGISTER* to submit the registration request. 

== Approve and Activate Users

. After a registration request is sent by the user, you will receive a notification email. To review and 
approve the user registration, navigate to the API community *ACM Administrator* interface.
. Select *Manage Users*. This section provides the status of all consumer developer registration requests.
. Select *Approve* to activate the user and trigger a welcome email.
After you approve the registration request, a welcome email is sent to the consumer developer. 
. To complete registration, the user must click an email verification link in the email and specify a new 
password. The consumer developer can then log in to your community. 
When the user's status is *Active*, additional options become available to the developer, such as *Forums* 
and *My Applications*.
. (Optional) To deactivate a user, disable the *Active* setting for that user.

== Searching Users

In the ACM administrator interface, the *Manage Members* tab shows a *Search Members* field.

Type one or more terms into the search field and the lists *Members* and *Pending Member Registration Requests* show only members matching all of the terms.

You can also filter the search results with these filter attributes:

* `fullName`
* `userName`

To use a filter attribute, type the attribute name, a colon, and the value for that attribute. For example, to show only members whose user name contains the substring "Smith", use the search term `userName:Smith`. This shows members with user names such as `jsmith@company.com` and `sue.jones@ironsmith.com`.

Search terms without a filter attribute apply to all fields of the member that are not filtered. For example, the search `userName:com Jones` shows members that have the substring "com" in the "Username" field and the substring "Jones" in any other field.
