= Manage Users
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Users self-register for access to the API Community Manager (ACM). Admins then approve users to give them access to the 
ACM user experience.

=== User Registration

When browsing a community as an unregistered or guest user, you can only view limited information.

Perform the following steps to self-register in a community:

. Navigate to the community.
. Select *Log in*.
. Select *Not a member?*
. Enter your community username and password.
. Select *REGISTER* to submit the registration request.

After the community administrator approves the registration request, a welcome email is sent to you. 
To complete registration, you must select the link in the email and specify a new password. You can 
then log in to the community using the account icon in the community navigation. As a registered user, 
additional options are now available, such as *Forums* and *My Applications*.

=== Admin Approval

Admins must perform the following steps to approve community registration requests:

.  Navigate to the API community *ACM Administrator* interface.
. Select *Manage Users*. This section provides the status of all developer registration requests.
. Select *Approve* for a request to be approved. To deactivate a current registration, disable the *Active* setting for that user.
