= Manage Users
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Consumer developers self-register for access to the API Community Manager (ACM). You can then approve users to give them access to the ACM developer features. 

== User Registration and Activation

When consumer developers browse your community as unregistered users (guests), they can view only limited information.

To give consumer developers access to your community, the following steps are performed:  

. Navigate to the community to which they want access.
. Select *Log in*.
. Select *Not a member?*
. Enter their community username and password. 
. Select *REGISTER* to submit the registration request. 
. After a registration request is sent, navigate to the API community *ACM Administrator* interface.
. Select *Manage Users*. This section provides the status of all developer registration requests.
. Select *Approve* to activate the user and trigger a welcome email.
After you approve the registration request, a welcome email is sent to the consumer developer. 
. To complete registration, the user must click the link in the email and specify a new password. The consumer developer can then log in to the community using the account icon in the community navigation. When the user's status is *Active*, additional options become available to the developer, such as *Forums* and *My Applications*.
. (Optional) To deactivate a current registration, disable the *Active* setting for that user.
