= Manage Members
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Consumer developers self-register for access to your Anypoint API Community
Manager community. You can then approve member registrations to give them
access to the restricted sections of your community.

NOTE: Registered members require a license. No license is required for guest
users. For full information about licenses, refer to
the xref:licensing-overview.adoc[Licensing Overview].

== Member Registration and Activation

When consumer developers browse your community as unregistered users (guests),
they can view only limited information.

Consumer developers follow these steps to self-register:

. Navigate to the community to which they want access.
. Select *Log in*.
. Select *Not a member?*
. Enter their community username and password.
. Select *REGISTER* to submit the registration request.

== Approve and Activate Members

. After the consumer developer sends a registration request, you receive a notification email.
. To review and approve the request, open the API Community Manager control panel and click *Member Management*.
. Open the *Members* tab to view a searchable list of current members, with the option to disable and enable their accounts.
. To deactivate a member, disable the *Active* setting for that member and confirm the change.
. Open the *Pending members registration* tab to view a searchable list of requests for access.
. To reject a registration request, select *Reject* and confirm the change.
+
A user whose request is rejected cannot request registration again for 30 days. To undo a rejection by retrieving the rejected request, enable *Show rejected users* and click *Retrieve*.
. To approve a request, select *Approve* and confirm the change.
. After you approve a registration request, a welcome email is sent to the consumer developer.
. To complete registration, the member must click an email verification link in the email and specify a new
password.
+
The consumer developer can then log in to your community.
When the member's status is *Active*, additional options become available to the developer, such as *Forums*
and *My Applications*.

== Searching Members

In the API Community Manager control panel, the *Member Management* tab shows a search bar. Enter one or more terms into the search field.

You can filter search results with the following filter attributes:

* `fullName`
* `userName`

To use a filter attribute, type the attribute name followed by a colon and the value for that attribute.
For example, filtering with `userName:Smith` only shows members with names that include "Smith",
such as `jsmith@company.com` and `sue.jones@ironsmith.com`.

Search terms without a filter attribute only apply to member fields that are not filtered. For example, the
search `userName:com Jones` shows members that include "com" in the "Username" field and "Jones" in any field
other than "Username".
