= Manage Members
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Consumer developers self-register for access to your API Community. You can then approve member registrations to give them access to the restricted sections of your community.

NOTE: Registered members require a license. No license is required for guest users. For full information about licenses refer to the xref:licensing-overview.adoc[Licensing Overview].

== Member Registration and Activation

When consumer developers browse your community as unregistered users (guests), they can view only limited information.

Consumer developers follow these steps to self-register:

. Navigate to the community to which they want access.
. Select *Log in*.
. Select *Not a member?*
. Enter their community username and password.
. Select *REGISTER* to submit the registration request.

== Approve and Activate Members

. After a registration request is sent by the member, you will receive a notification email. To review and
approve the member registration, navigate to the ACM Control Panel.
. Select *Manage Members*. This section provides the status of all consumer developer registration requests.
. Select *Approve* and confirm the change to activate the member and trigger a welcome email.
After you approve the registration request, a welcome email is sent to the consumer developer.
. To complete registration, the member must click an email verification link in the email and specify a new
password. The consumer developer can then log in to your community.
When the member's status is *Active*, additional options become available to the developer, such as *Forums*
and *My Applications*.
. (Optional) To deactivate a member, disable the *Active* setting for that member and confirm the change.

== Searching Members

In the ACM Control Panel, the *Manage Members* tab shows a *Search Members* field.

Enter one or more terms into the search field. Search results are listed in *Members* and *Pending Member Registration Requests*.

You can filter search results with the following filter attributes:

* `fullName`
* `userName`

To use a filter attribute, type the attribute name followed by a colon and the value for that attribute.
For example, filtering with `userName:Smith` only shows members with names that include "Smith",
such as `jsmith@company.com` and `sue.jones@ironsmith.com`.

Search terms without a filter attribute only apply to member fields that are not filtered. For example, the
search `userName:com Jones` shows members that include "com" in the "Username" field and "Jones" in any field
other than "Username".
