= Manage Users
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Consumer developers self-register for access to the API Community Manager (ACM). You can then approve users to give them access to the ACM developer features. 

== User Registration and Activation

When consumer developers browse your community as unregistered users (guests), they can view only limited information.

Consumer developers follow these steps to self-register:  

. Nvigates to the community to which they want access.
. Selects *Log in*.
. Selects *Not a member?*
. Enters their community username and password. 
. Selects *REGISTER* to submit the registration request. 

== Approve and Activate Users

. After a registration request is sent by the user, navigate to the API community *ACM Administrator* interface.
. Select *Manage Users*. This section provides the status of all developer registration requests.
. Select *Approve* to activate the user and trigger a welcome email.
After you approve the registration request, a welcome email is sent to the consumer developer. 
. To complete registration, the user must click the link in the email and specify a new password. The consumer developer can then log in to the community using the account icon in the community navigation. When the user's status is *Active*, additional options become available to the developer, such as *Forums* and *My Applications*.
. (Optional) To deactivate a current registration, disable the *Active* setting for that user.
