= Publish APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

An ACM community administrator imports APIs, minor API updates, and major API updates from their Exchange organization to their community, reviews them, and publishes them.

== Import APIs

Open the ACM administrator interface and select the *Manage APIs* tab at the top left.

On this tab you can manage the APIs in your community, including their metadata and visibility.

The section *APIs in this Community* shows the API versions that have been added to the community.

The section *APIs in Exchange* shows the API versions that exist in your Exchange organization and have not been added to the community.

To add an API version from Exchange to the community, click the *Add to Community* button to the right of the API version name.

The API version is now listed in the *APIs in this Community* section. *Visibility* is set to *Admin Only*, the API version has no icon, and the *Description* is blank. The following sections describe how to update the visibility, icon, and description information.

== Set API Information

Click the *Edit* button to the right of the API version name.

Optionally, edit the *API Name*.

Click *Replace Icon* to set the API version icon.

Add a *Description* for the API version.

For now, leave the *Visibility* as *Admin Only* while you preview the API version.

By default, each API version on your community's page has a link (labeled "API Details") to a page showing information about the API. To preserve this default, set *Marketing Page* to *None*. To link to a different CMS content page in your community such as a marketing page, set the *Marketing Page* option to *CMS/Custom page* and fill in the URL of the CMS page.

Click the *Apply* button at the bottom right.

== Preview APIs

In the ACM administrator interface, select *Community Builder* at the top.

The community builder shows a preview of your community's site and options to edit the site.

Click *Preview* at the top right to enter preview mode.

Scroll down to the API carousel that shows a card for each API version in the community.

The new API version shows the message *This is only visible for you*, showing that the API version visibility is *Admin Only*. Consumer developers viewing the page do not see this API version.

== Make API Versions Visible

In the ACM administrator interface, select *Manage APIs* at the top.

Click the *Edit* button to the right of the API version name.

Set *Visibility* to *Public*.

Click the *Apply* button at the bottom right.

Consumer developers now see this API version in the API carousel on the community site.

== Minor API Updates

When an API specification or its documentation need corrections such as changing the text, these non-breaking changes are given a minor version change, such as changing version `3.0.0` to version `3.0.1`. ACM automatically and immediately imports these updates to all communities where that API is published, without requiring any action from the ACM administrator.

For example, suppose both the text in an API's documentation and the text in the API Specification description have spelling errors.

To correct errors in the API specification, open Design Center, open the API project, and fix the spelling in the description.

Click the *Publish to Exchange* button at the top right.

In the dialog box *Publish API specification to Exchange*, leave the existing *Name*, *Main file*, and *API Version*, and increment the *Asset version* for a non-breaking change. For example, if the *Asset version* is `3.0.0`, change it to `3.0.1`.

Click the *Publish* button at the bottom right.

To correct errors in the API documentation, open Exchange, open the API, click the *Edit* button at the top right, and fix the errors.

Click the *Save as draft* button at the bottom right.

Click the *Publish* button at the top right.

Consumer developers now see the corrected information on the community site.

== Major API Updates

When a new version of the API with breaking changes is created, the ACM community administrator controls when and how to publish the new version in the community, mark the old version as deprecated, and remove the old version.

Suppose a developer on the API team adds a new resource to an API.

In Design Center, the developer opens the API project, adds the resource to the specification, and clicks the *Publish to Exchange* button at the top right.

This is a breaking change, so in the dialog box *Publish API specification to Exchange* the developer changes the *API version*. For example, if the *API version* is `v3`, it becomes `v4`. If the *Asset version* is `3.0.1`, it becomes `4.0.0`. *Name* and *Main file* do not change.

The developer clicks the *Publish* button at the bottom right.

The previous API version v3 remains in all communities where it was published without any changes.

In the ACM administrator interface, select *Manage APIs* at the top.

The previous API version v3 remains unchanged in the section *APIs in this Community*.

The new API version v4 is listed in the section *APIs in Exchange*.

To add version v4 to the community, click the *Add to Community* button to the right of the API version name.

The API version v4 is now listed in the section *APIs in this Community*.

Click the *Edit* button to the right of the API version v4 name and set the *Icon*, *Description*, *Visibility*, and *Marketing Page* as you did for version v3.

Preview the API, and then set *Visibility* to *Registered users* or *Public*.

Consumer developers now see API version v4 in the API carousel on the community site.

To mark version v3 as deprecated, click the *Edit* button to the right of the API version v3 name, add `[DEPRECATED]` to the end of the *API Name*, and click the *Apply* button in the bottom right.

To remove version v3 from your community, click the *Remove* button to the right of the API version v3 name, and in the dialog box click *Remove* again to confirm. Consumer developers now do not see API version v3 in the API carousel on the community site.
