= Publish APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

ACM community administrators import APIs, import minor and major API updates from the Exchange 
organization to a community, and review and publish the imported information.

== Import APIs

. Open the ACM administrator interface and select *Manage APIs*. From this tab, you can manage the APIs in your 
community, including their metadata and visibility.

* *APIs in this Community* shows the API versions that have been added to the community.
* *APIs in Exchange* shows the API versions that exist in your Exchange organization but have not been 
added to the community.
. Select *Add to Community* next to the API version name. The API version is now listed in the *APIs in 
this Community* section. *Visibility* is set to *Admin Only*, the API version has no icon, and the *Description* is blank.

Now set the API information, including visibility, icon, and description.

== Set API Information

. Select *Edit* next to the API version name.
. Optionally, edit the *API Name*.
. Select *Replace Icon* to set the API version icon.
. Enter a *Description* for the API version.
. Leave the *Visibility* as *Admin Only* while you preview the API version.
. By default, each API version on your community's page has an *API Details* link. To preserve this default, set *Marketing Page* to *None*. To link to a different CMS content page in your community, such as a marketing page, set the *Marketing Page* option to *CMS/Custom page* and enter the URL of the CMS page.
. Select *Apply*.

== Preview APIs

. In the ACM administrator interface, select *Community Builder*. The Community Builder displays a preview of 
your community's site and edit options.
. Select *Preview*.
. Scroll to the API carousel that displays a card for each API version in the community. The new API version 
shows the message *This is only visible for you*, indicating *Admin Only* visibility. Consumer developers cannot 
see this API version preview.

== Make API Versions Visible

. In the ACM administrator interface, select *Manage APIs*.
. Select *Edit* next to the API version name.
. Set *Visibility* to *Public*.
. Select *Apply*. Consumer developers can now see this API version in the API carousel on the community site.

== Minor API Updates

When an API specification or documentation requires non-breaking corrections, such as changing the text, these changes are given a minor version change, such as `3.0.0` to version `3.0.1`. ACM automatically and immediately imports these updates to all communities in which the API is published, without requiring any action from the ACM administrator.

For example, suppose both the text in an API's documentation and the text in the API Specification description have spelling errors.

To correct errors in the API specification:

. Open the *Design Center*.
. Open the API project and fix the errors.
. Select *Publish to Exchange*.
. In the *Publish API specification to Exchange* dialog box, leave the existing *Name*, *Main file*, and *API Version*, 
but increment the *Asset version* for a non-breaking change. For example, change `3.0.0` to `3.0.1`.
. Select *Publish*.

To correct errors in the API documentation:

. Open Exchange.
. Open the API.
. Select *Edit* and fix the errors.
. Select *Save as draft*.
. Select *Publish*.

Consumer developers now see the corrected information on the community site.

== Major API Updates

When a new version of the API with breaking changes is created, the ACM community administrator controls 
when and how to publish the new version in the community, mark the old version as deprecated, and remove the old version.

For example, suppose a developer on the API team adds a new resource to an API.

. In *Design Center*, the developer opens the API project, adds the resource to the specification, and selects 
*Publish to Exchange*.
. Because this is a breaking change, the developer changes the *API version* information in *Publish API specification 
to Exchange*. For example, if the *API version* is `v3`, it becomes `v4`. If the *Asset version* is `3.0.1`, it 
becomes `4.0.0`. *Name* and *Main file* do not change.
. The developer selects *Publish*. The previous API version remains in all communities where it was published 
without any changes.

The ACM community administrator must then review and publish the changes:

. In the ACM administrator interface, select *Manage APIs*. The previous API version remains unchanged in 
*APIs in this Community*. The new API version is listed in *APIs in Exchange*.
. To add the new version to the community, select *Add to Community* next to the new API version name. The new API version
is now listed in *APIs in this Community*.
. Select *Edit* next to the new API version name and set the *Icon*, *Description*, *Visibility*, and *Marketing Page* 
as you did for the previous version.
. Preview the API.
. Set *Visibility* to *Registered users* or *Public*. Consumer developers can now see the new API version 
in the API carousel on the community site.
. To mark the previous version as deprecated, select *Edit* next to the previous API version name.
. Append `[DEPRECATED]` to the *API Name*, and select *Apply*.
. To remove the previous version from your community, select *Remove* next to the previous API version name.
. Select *Remove* again to confirm. Consumer developers can no longer see the previous API version in 
the API carousel on the community site.

== Searching APIs

In the ACM administrator interface, the *Manage APIs* tab shows a *Search APIs* field.

Type one or more terms into the search field and the lists *APIs in This Community* and *APIs in Exchange* show only APIs matching all of the terms.

You can also filter the search results with these filter attributes:

* `name`
* `version`
* `description`
* `businessGroup`

To use a filter attribute, type the attribute name, a colon, and the value for that attribute. For example, to show only APIs whose name contains the substring "order", use the search term `name:order`. This shows APIs with names such as "Order Status API" or "Received Orders".

Search terms without a filter attribute apply to all fields of the API that are not filtered. For example, the search `businessGroup:Sales banking` shows APIs that have the substring "Sales" in the "Business Group" field and the substring "banking" in any other field.
