= Publish APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

As an Anypoint API Community Manager community administrator, you can add and publish APIs and API groups and minor and major updates from Anypoint Exchange into your community. 

This information includes the API documentation stored with the APIs in Exchange.
The API documentation is separate from the articles stored in the Salesforce
content management system (CMS). The API release process includes API
documentation updates, and the CMS article release process is usually separate.
Often a development team will lead the API release process and a marketing team
will lead the CMS article release process.

== Add APIs or API Groups from Exchange to Your Community

. Open the API Community Manager control panel and select *Manage APIs*.
+
From this tab, you can manage the APIs in your community, including their metadata and visibility.
+
* *APIs in this Community* shows the API versions that have been added to the community.
* *APIs in Exchange* shows the API versions that exist in your Exchange organization but have not been added to the community.
. Select a version of the API and click *Add to Community* next to the API name.
+
The API version is now listed in the *APIs in this Community* section. *Visibility* is set to *Admin Only*, the API version has no icon, and the *Description* is blank.
. Set the API information, including visibility, icon, and description.

== Set API Information

. Select *Edit* next to the API version name.
. Optionally, edit the *API Name*.
. Select *Replace Icon* to set the API version icon.
. Enter a *Description* for the API version.
. Leave the *Visibility* as *Admin Only* while you preview the API version as described in the next section.
. When your API is displayed on the community site in the API Carousel component or in an API card, by default it has a single *API Details* button. It can also have an optional *Learn more* button that links to a business content page. In the *Associated "Learn-more" Page* section, select *None* to keep the default, or select *Custom page* and set the *Custom page URL* to a business content page created in Community Builder.
. Select *Apply*.

== Preview APIs

. In the API Community Manager control panel, click *Community Builder*.
+
Community Builder displays a preview of your community's site and edit options.
. Select *Preview*.
. Scroll to the API carousel that displays a card for each API version in the community.

The new API version shows the message *This is only visible for you*, indicating *Admin Only* visibility. Consumer developers cannot see this API version preview.

If no changes are visible, xref:troubleshooting.adoc#refresh-the-cache[refresh the cache].

== Make API Versions Visible

. In the API Community Manager control panel, select *Manage APIs*.
. Select *Edit* next to the API version name.
. Set *Visibility* to *Everyone* if you want it to be publicly available, or *Members only* if you want it to be seen only by logged-in members.
. Select *Apply*.

Consumer developers can now see this API version in the API carousel on the community site.

== Minor API Updates

When an API specification or documentation requires nonbreaking corrections, such as changing the text, these changes are given a minor version change, such as from `3.0.0` to `3.0.1`. API Community Manager automatically and immediately imports these updates to all communities in which the API is published, without requiring any action from the API Community Manager administrator.

For example, suppose both the text in an API's documentation and the text in the API Specification description have spelling errors.

To make corrections in the API specification:

. Open the *Design Center*.
. Open the API project and fix the errors.
. Select *Publish to Exchange*.
. In the *Publish API specification to Exchange* dialog box, leave the existing *Name*, *Main file*, and *API Version*,
but increment the *Asset version* for a non-breaking change. For example, change `3.0.0` to `3.0.1`.
. Select *Publish*.

To make corrections in the API documentation:

. Open Exchange.
. Open the API.
. Select *Edit* and fix the errors.
. Select *Save as draft*.
. Select *Publish*.

Consumer developers see the corrected information on the community site immediately.

If no changes are visible, xref:troubleshooting.adoc#refresh-the-cache[refresh the cache].

== Major API Updates

When a new version of the API with breaking changes is created, the API Community Manager community administrator controls
when and how to publish the new version in the community, mark the old version as deprecated, and remove the old version.

For example, suppose a developer on the API team adds a new resource to an API.

. In *Design Center*, the developer opens the API project, adds the resource to the specification, and selects
*Publish to Exchange*.
. Because this is a breaking change, the developer changes the *API version* information in *Publish API specification
to Exchange*.
+
For example, if the *API version* is `v3`, it becomes `v4`. If the *Asset version* is `3.0.1`, it
becomes `4.0.0`. *Name* and *Main file* do not change.
. The developer selects *Publish*.
+
The previous API version remains in all communities where it was published without any changes.

The API Community Manager community administrator must then review and publish the changes:

. In the API Community Manager control panel, select *Manage APIs*.
+
The previous API version remains unchanged in *APIs in this Community*. The new API version is listed in *APIs in Exchange*.
. To add the new version to the community, select the version from the drop-down and select *Add to Community* next
to the API name.
+
The new API version is now listed in *APIs in this Community*.
. Select *Edit* next to the new API version name and set the *Icon*, *Description*, *Visibility*, and *Marketing Page*
as you did for the previous version.
. Preview the API.
. Set *Visibility* to *Registered users* or *Public*.
+
Consumer developers can now see the new API version in the API carousel on the community site.
. To mark the previous version as deprecated, select *Edit* next to the previous API version name.
. Append `[DEPRECATED]` to the *API Name*, and select *Apply*.
. To remove the previous version from your community, select *Remove* next to the previous API version name.
. Select *Remove* again to confirm.
+
Consumer developers can no longer see the previous API version in the API carousel on the community site.

If no changes are visible, xref:troubleshooting.adoc#refresh-the-cache[refresh the cache].

== Searching APIs and API Groups

In the API Community Manager control panel, the *Manage APIs* tab shows a *Search APIs* field.

Enter one or more terms into the search field. Search results are listed in *APIs in This Community* and *APIs in Exchange*.

You can filter search results with the following filter attributes:

* `name`
* `version`
* `description`
* `businessGroup`

To use a filter attribute, type the attribute name followed by a colon and the value for that attribute.
For example: filtering with `name:order` only shows APIs with names that include "order", such
as "Order Status API" or "Received Orders".

Search terms without a filter attribute only apply to API fields that are not filtered. For example, the
search `businessGroup:Sales banking` shows APIs that include "Sales" in the "Business Group" field and
"banking" in any field other than "Business Group".
