= Publish Content and CMS Articles
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

With API Community Manager (ACM), you can create, organize, and publish content, including news,
tutorials, developer blog posts, and events, for your community.

This content is stored in https://help.salesforce.com/articleView?id=community_managed_content_overview.htm&type=5[Salesforce content management system (CMS), role=external, window=blank] articles.
These articles are separate from the API documentation stored in Exchange.
The API release process includes API documentation updates, and the CMS article
release process is usually separate. Often a development team will lead the API
release process and a marketing team will lead the CMS article release process.

== Create a New Article in Salesforce CMS

NOTE: You can also author ACM content in https://help.salesforce.com/articleView?id=communities_cms_connect.htm&type=5[an external CMS system through CMS Connect, role=external, window=blank].

. Open the ACM control panel.
. Select *Manage CMS Content*. The Salesforce Community Cloud *Content Management* interface is displayed.
The *Content Management* interface is organized into these panels:

* *Content*: Lists each article in your community.
* *Collections*: Lists collections in your community, such as *News* for news articles and *Blogs* for blog posts. Each collection is a list of articles.
* *Topics*: Lists article Topic groupings. Topics are similar to tags.
* *Recommendations*: Drives community engagement by recommending videos, trainings, events, and more for your users.
. Select *Salesforce CMS*. The *Salesforce CMS* interface displays the workspaces in your Salesforce organization.
TIP: The *Salesforce CMS* interface enables other teams, such as marketing or business development, to own the creation and publication of content articles in a single place, and reuse content across multiple communities.
. Select the workspace in which you want to create the new article. A tab for that workspace is displayed
that contains a list of the workspace's content articles.
. Select *Add Content*.
. Fill in the article's *Title*, *Body*, *Featured Image*, and *Excerpt*. The *Excerpt* is the preview text on an article's carousel tile.
. When finished with your changes, select *Save Draft*. You can edit and save the draft again any number of times.
. When you are ready to publish the article, select *Publish*.

== Add the Article to a Collection

. Open the ACM control panel.
. Select *Manage CMS Content*. The Salesforce Community Cloud *Content Management* interface is displayed. It shows a list of your community's articles.
. Select *Collections*.
. Select the appropriate collection for your article.
. Select *Edit*. Articles selected to be part of the collection have green check marks to the left of their names.
. Select the plus sign (`+`) next to your new article to add it to the collection.
. Select *Save*.

The collection now lists your new article.

The https://help.salesforce.com/articleView?id=community_managed_content_collections.htm&type=5[Salesforce Community Cloud documentation, role=external, window=blank] describes additional ways to add articles to collections, and includes more advanced categorization capabilities using topics and rules.

== Display the Collection in Your Community

. Open the ACM control panel.
. Click *Community Builder*. A preview of your community's site is displayed.
. If the collection containing your new article is already displayed in a *CMS Collection* component, then your new article will be visible there.
. Your article will be visible in any new *CMS Collection* components displaying the collection containing the article.

== Create Collections to Organize Content

. Open the ACM control panel.
. Select *Manage CMS Content*.
. Select *Collections*.
. Select *New*.
. Enter a name for your collection, select the source *CMS Content*, and choose to curate the collection *Manually*.
. From the list of community articles, select the ones you want to include in the collection by selecting the plus sign (`+`) next to each article.
. Select *Finish*.
. To use your new collection on your community site, open the ACM control panel and click *Community Builder*.
. Add a *CMS Collection* component to a page in your community.
. Select the component to open its configuration menu, and select *Change Collection* to select your new collection.

The new collection of articles is now displayed on your community page.

== External CMS Systems

You can also author ACM content in https://help.salesforce.com/articleView?id=communities_cms_connect.htm&type=5[an external CMS system through CMS Connect, role=external, window=blank].

External CMS systems can include Adobe Experience Manager, Drupal, Wordpress, and others.

You can learn more about CMS Connect on Trailhead with the trail https://trailhead.salesforce.com/en/content/learn/modules/partner-relationship-management/deploy-fast-and-personalize-the-experience[Deploy Fast and Personalize the Experience, role=external, window=blank].

== See Also

* https://help.salesforce.com/articleView?id=community_builder_manage_pages_overview.htm&type=5[Manage Your Community's Pages and Their Properties in Community Builder, role=external, window=blank]
* https://help.salesforce.com/articleView?id=community_managed_content_overview.htm&type=5[Salesforce Content Management System (CMS) (Beta), role=external, window=blank]
