= Publish Your Site
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

After you edit and preview your updated Salesforce Experience Cloud site, you can publish the new version for your users:

. Open the Anypoint API Community Manager control panel.
+
If you don't see *API Community Manager* in *App Launcher*, follow xref:manual-setup.adoc#enable-api-community-manager-control-panel[Enable API Community Manager Control Panel].
. Click *Shortcuts to applications* and select *Site Builder*.
. Click *Settings* > *General*.
. Select the *Public can access the community* check box.
. Return to *Site Builder*.
. Click *Publish*.

If your community is not already active, activate it:

. Open the API Community Manager control panel.
. Click *Shortcuts to applications* and select *Site Administration*.
. Click *Settings*.
. Click *Activate*.

After your community is published and active, view the live site:

. Open the API Community Manager control panel.
. Click *Shortcuts to applications* and select *Open Site*.
