= Salesforce Releases and Migrations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

The Salesforce organization dedicated to your API community follows the standard https://trailhead.salesforce.com/en/content/learn/modules/sf_releases/sf_releases_start[Salesforce release process]. This automatically upgrades your organization to the latest Salesforce release version three times each year. As an organization administrator, you'll receive email notifications about the changes at least three months in advance, including any required steps for you to follow, guidance, and other resources.

If any additional steps are required to prepare Anypoint API Community Manager, they will be provided from your MuleSoft customer success representative and on https://status.mulesoft.com/[trust.mulesoft.com]. Many Salesforce upgrades do not require any additional steps for API Community Manager.

== Salesforce Organization Migrations

The Salesforce organization dedicated to your API community may sometimes need to move across instances within a region. These migrations usually have no impact on your API community. If a migration has any impact, you will be notified by your MuleSoft customer success representative and on https://status.mulesoft.com/[trust.mulesoft.com].

== Getting Help

For help with the Salesforce release or migration process, contact your customer success representative. For outages or operational issues with your API community, contact MuleSoft support.

== See Also

* https://trailhead.salesforce.com/en/content/learn/modules/sf_releases/sf_releases_start[Salesforce release process]
