= Sandboxes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Upgrades are applied automatically to Anypoint API Community Manager versions 2.0 and later.

Upgrades with new features are applied to sandbox environments four weeks before they are applied to production environments. Upgrades with only bug fixes are applied to sandbox environments two weeks before they are applied to production environments.

== Sandboxes for Upgrading from Version 1.x

After you install an Anypoint API Community Manager upgrade, it is not possible to undo the installation
and revert to a previous version. Therefore, be sure to create safe sandbox environments in which you test each
upgrade before installing it in your production environment.

=== New Sandboxes

To create a new sandbox:

. In *Setup*, search for *Sandboxes* using the *Quick Find* box and click *New Sandbox*.
. Enter a name and description and create a new developer sandbox.
+
After several minutes to a few hours, sandbox creation completes and sends you a notification email.
. In *Setup*, search for *Sandboxes* using the *Quick Find* box and log in to your new sandbox with your administrator password.
+
Note that the user name has the sandbox name as a suffix.

To validate your new sandbox:

. Open the application launcher.
. Open the *API Community Manager* application.
. Publish a few APIs.
. Open the builder.
. Publish your community.
. Open your community's live site.
. Validate the site is operational.

After validating your new sandbox, begin the upgrade.

=== Upgrade Workflow

To test and install each upgrade:

. Keep a long-term staging environment sandbox with either a partial copy or a full copy of the data in the production environment.
. Create a short-term developer sandbox.
. Install the upgrade in the developer sandbox and test it.
. Discard the developer sandbox.
. Install the upgrade in the staging sandbox and test it.
. Install the upgrade in your production environment.

== See Also

* xref:update-acm.adoc[Upgrade API Community Manager]
