= Optionally Configure Search in CMS Content
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

You can enable the Salesforce CMS content manager, provide topics to organize the content, and enable Salesforce CRM content.

Your profile should have all the CMS application permissions:

* Manage Content Permissions: Create, edit, and delete library permissions in Salesforce CRM Content.
* Manage Content Properties: Create, edit, and delete custom fields in Salesforce CRM Content.
* Manage record types and layouts for Files: Create, edit, and delete content types in Salesforce CRM Content.
* Manage Salesforce CRM Content: Create, edit, and delete libraries and library memberships.

Enable Salesforce CMS for Anypoint API Community Manager:

. If you have not already configured the CMS content:
.. In the admin go to CMS administrator
.. If you have No content available yet, go to Salesforce CMS App and select CMS Workspaces
.. Click on `Add Workspace` and enter the name and description of the work	space and click next.
.. Select the channels (all the communities in which you want to search the CMS content)
.. Add the contributors if you have.
.. Choose the languages for your translated content and click next.
.. Review the information to make sure it's accurate and click done.
.. Now you should create a new collection and upload content.
. In CMS channel make the community channel searchable, for that, go to CMS Channels and edit the channel to enable search and click save.
. Add the community url to remote site settings, copy the community url and in Setup go to Remote Site Settings and add a new site with that url.
. Verify your user must have the option Salesforce CRM Content User enable
. In the builder select the ACM Search Box and enable the option Search in Managed Content

If you have any doubt please follow the documentation from
https://help.salesforce.com/articleView?id=community_managed_content_overview.htm&type=5[Salesforce CMS] or follow
https://docs.mulesoft.com/api-community-manager/publish-content[this page].
