= Security
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Anypoint API Community Manager uses the same secure hardware, backup, disaster recovery, and business continuity
systems as Salesforce and Anypoint Platform.

API Community Manager is part of Anypoint Platform, and each member has one Anypoint Platform account, which is also used as their API Community Manager account.

All connections between API Community Manager and related systems, such as Salesforce and Anypoint Exchange, are encrypted with
Transport Layer Security (TLS).

During initial configuration, you can set API Community Manager to use a third party single sign-on (SSO) provider, such as Okta,
for member connections to both Anypoint Platform and Salesforce systems.

Anypoint Access Management configures xref:access-management::external-identity.adoc[Identity Management] for single sign-on (SSO) in MuleSoft, and supports xref:access-management::ldap-configuration-index.adoc[LDAP] and other standards.

Anypoint API Manager applies xref:api-manager::policies-mule4.adoc[policies] to APIs for security, and supports xref:api-manager::mule-oauth-provider-landing-page.adoc[OAuth 2.0] and other standards.

If you discover a security vulnerability, follow the steps in https://help.mulesoft.com/s/article/How-to-Report-Vulnerabilities-or-Security-Issues-on-Mule-Products[How to Report Vulnerabilities or Security Issues on Mule Products, role=external, window=blank] to send a report to security@salesforce.com with detailed steps to reproduce the vulnerability.

== See Also

* https://trust.salesforce.com/en/security/[Salesforce Security, role=external, window=blank]
