= Security
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

API Community Manager (ACM) uses the same secure hardware, backup, disaster recovery, and business continuity
systems as Salesforce and the Anypoint Platform.

ACM is part of Anypoint Platform, and each member has one Anypoint Platform account, which is also used as their ACM account.

All connections between ACM and related systems, such as Salesforce and Anypoint Exchange, are encrypted with
Transport Layer Security (TLS).

During initial configuration, you can set ACM to use a third party single sign-on (SSO) provider, such as Okta,
for member connections to both the Anypoint Platform and Salesforce systems.

Anypoint Access Management configures xref:access-management::external-identity.adoc[Identity Management] for single sign-on (SSO) in MuleSoft, and supports xref:access-management::ldap-configuration-index.adoc[LDAP] and other standards.

Anypoint API Manager applies xref:api-manager::policies-mule4.adoc[policies] to APIs for security, and supports xref:api-manager::mule-oauth-provider-landing-page.adoc[OAuth 2.0] and other standards.

// Add more discussion of the process when a consumer developer requests access to an API for an application?

// Is OAuth token exchange used anywhere?

== See Also

* https://trust.salesforce.com/en/security/[Salesforce Security, role=external, window=blank]
