= Set Up and Register a Domain and Enable Communities
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

To set up and register a domain:

. Log in to your API Community Manager https://login.salesforce.com/[Salesforce Organization, role=external, window=blank].
. Go to *Salesforce Set-up* by selecting the gear icon and selecting *Set-up*.
. Search for *My Domain* using the *Quick Find* box and then select *My Domain*.
. Enter a domain name for your organization. The name can include up to 34 letters, numbers, and hyphens.
. Select *Check Availability*. If the name is already taken, choose a different one.
. Select *Register Domain*.

You will receive a notification email when your domain is registered and your
subdomain name is ready for testing. This process can take a few minutes.
You can continue with the next steps while you wait for the email.

NOTE: After you complete API Community Manager installation and configuration, you can configure a full custom domain
name, also known as a vanity domain. When you're ready, refer to the Salesforce knowledge article
https://help.salesforce.com/articleView?id=000336819&type=1&mode=1[Run your Salesforce Community under a custom domain, role=external, window=blank].

Using the domain name you selected in the previous step, follow the steps in
https://help.salesforce.com/articleView?id=networks_enable.htm&type=5[Enable Salesforce Communities, role=external, window=blank]
to enable communities inside your Salesforce organization.
