= Set Up Impersonation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

// Needs intro sentence

. Create a Connected App

.. In Anypoint Platform, navigate to *Access Management* -> *Applications* -> *Create New Application*. 
.. Provide the following information:

*** *Application Name*: Enter a name.
*** *Redirect URIs*: This URL can be found in the Authentication Provider configuration. Navigate 
to *Salesforce Setup* -> *Auth. Providers* -> *Anypoint* -> *Callback URL*. 
*** *User Grant Types*
**** *Authorization Code*: Checked.
**** *Refresh Token*: Checked.
**** *Full Access*: Checked
**** *Background Access*: Checked.

.. Select *Create Application*.

... Curl example:
    
    `curl -X POST \
      https://anypoint.mulesoft.com/accounts/api/connectedApplications \
      -H 'Accept: */*' \
      -H 'Accept-Encoding: gzip, deflate' \
      -H 'Authorization: Bearer ***token***' \
      -H 'Host:anypoint.mulesoft.com' \
      -d '{"client_name":"SalesforceApp","grant_types":["authorization_code","refresh_token"],"redirect_uris":["https://OrgDomain.my.salesforce.com/services/authcallback/Anypoint"],"scopes":["full","offline_access"],"public_keys":[]}`

. Configure Auth Provider (Salesforce)

.. From the Salesforce interface, navigate to *Setup* -> *Auth. Providers* -> *Anypoint* -> *Edit*.
.. Provide the following information:
... *Consumer Key*: The application ID of the Connect App created in Anypoint.
... *Consumer Secret*: The application secret of the Connect App created in Anypoint.
... *Authorize Endpoint URL*: `https://anypoint.mulesoft.com/accounts/api/v2/oauth2/authorize`
... *Token Endpoint URL*: `https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token`
... *Default Scopes*: `full offline_access`.

    NOTE: Remember to associate the External Datasource with this Auth provider.

. Configure IDP

** Using SAML, an IDP must be configured in both Anypoint and Salesforce. You can use Salesforce as an IDP.

.. Setting up SAML

... Register an app for SAML in Salesforce:

.... Navigate to the *Setup* page.
.... Select *App Manager*.
.... Select *New Connected App*.
.... Provide the following Basic Information:

***** Connected App Name : This automatically populates the API Name, such as `Anypoint`.
***** Contact Email
.... Under Web App Settings:

..... Provide the *Start URL*: `https://anypoint.mulesoft.com/accounts/login/<your_anypoint_domain_name>` or the location 
where you want users to be sent in the Anypoint Platform.
..... Select *Enable SAML*.
.... Provide any string as *Entity Id*. This is also the Audience configuration in the Anypoint Platform.
.... Provide the *ACS URL*. SAML assertions are sent to the ACS URL. For Anypoint: 
`https://anypoint.mulesoft.com/accounts/login/receive-id`.
.... Select *Enable Single Logout*.
.... Provide *Single Logout URL*: `https://anypoint.mulesoft.com/accounts/logout/receive-id`.
.... Set *Single Logout Binding* to *HTTP Post*.
.... Set *Subject Type* to *Username*.
.... Set *Name ID* Format to *unspecified nameID format*.
.... Set *Issuer* to *salesforce_org_domainname*.
.... Set *IdP Certificate* to *Default IdP Certificate*.
.... Select *Save*.

... Set Up Custom Attributes:

**** By default, Salesforce does not send first name and last name attributes, so you must add them.

.... Select *Manage* for your app.
.... Scroll to *Custom Attributes*.
.... Select *New*. Type `firstname`. Click *Insert Field*. Select *$User >* -> *First Name* -> *Insert* -> *Save*.
.... Select *New*. Type `lastname`. Click *Insert Field*. Select *$User >* -> *Last Name* -> *Insert* -> *Save*.

... Configure Anypoint account with external identity with SAML:

.... Navigate to your Salesforce app enabled for SAML and select *Manage* to see all the URIs to be used to set up 
external identity in Anypoint. Make a note of these URIs for quick reference.
.... Switch to your Anypoint account. Navigate to 
*Access Management* -> *External Identity* -> *Identity Management* -> *SAML 2.0*.
.... Set *Sign On URL* to *IdP-Initiated Login URL*.
.... Set *Sign Off URL* to *Single Logout Endpoint*.
.... Set *Issuer* to match the Salesforce account: `salesforce_org_domainname`.
.... To find your Public Key, find Identity Provider, select *Download certificate*, and 
open the certificate in a text editor. Copy all of the content and paste it into the *Public Key* field. 
Alternatively, you can download metadata from the Salesforce app and extract the certificate from it.
.... Set *Audience* to match the *Entity Id* you set in the Salesforce account.
.... Select *Save*.

. Configure and Authorize ODATA Bridge to Perform Impersonation

** This final step requires a private key or a certificate, and a keystore (JKS) containing that key or certificate. Use the same certificate that Salesforce IDP uses.

.. In *Salesforce Setup*, search for *Certificate and Key Management* using the *Quick Find* box .
.. Select *Export to Keystore*.
.. Enter a new Password.
.. Select *Export*.

.. Import Keystore in Secrets Manager

... In Anypoint, go to *Access Management* -> *Environments*.
... Select *Add Environment* and provide the following information:

**** Set *Environment Name* to `ACM`.
**** Select *Production*.
... Select *Create*.
... Select *Users*.
... Select your user.
... Select *Secrets Manager*.
... Set *Environment* to the newly created environment: `ACM`.
... Select all permissions in *Permissions*.
... Select the plus button.
... To apply these changes, log out and then log back in.
... In Anypoint, select *Secrets Manager*.
... Select the desired environment using the environment switcher.
... Select *Create Secret Group*.
... Set *Name* to *Certificates*.
... Select *Secret Group Downloadable*.
... Select *Save*.
... Select *Keystore*.
... Select *Add Keystore*.
... Provide the following information:

**** *Name*: Enter `Impersonation`.
**** *Type*: Enter the type of your keystore, which is typically JKS.
**** *Keystore File*: Choose your keystore file, which is typically the file you exported from Salesforce.
**** *Keystore Passphrase*: Enter the exported Keystore.
**** *Alias*: Choose the corresponding alias to your key or certificate.
**** *Key Passphrase*: Create a new Keystore.

... Select *Save*.
... Select *Secret Groups*.
... Select *Finish* on the recently created secret group and confirm the operation.

*** For detailed information about creating secret groups and adding certificates, refer to 
https://docs.mulesoft.com/anypoint-security/asm-secret-group-creation-task#create-a-secret-group[Create a Secret Group (Anypoint Platform), role=external, window=_blank].

.. Mapping Community User to Anypoint Role

... Navigate to *Access Management* and select *Roles*.
... In *Exchange Viewers*, set a new External group called `Community User` and save it.

... *IMPORTANT*: If you choose to use another key or certificate for the impersonation feature, 
you must add this key in the External Identity configuration on Anypoint, as shown in the following steps:

.... In Anypoint, select *Access Management* -> *External Identity* -> *Edit*. 
.... Add your key in *Public Key*:

..... Copy the key with no line breaks.
..... After the key displayed in the *Public Key* field, add a comma (,) and then paste in the new key.
..... Select *Save*.

// For more information about this feature, see the User Impersonation link section of the architecture documentation.
