= Issues with Branded Emails 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/


When the change data capture is enabled, Salesforce starts polling the ACM Community Bridge for contract updates. The following information includes symptoms and troubleshooting steps for troubleshooting branded emails.

== Data Capture Process Fails

If the data capture process job fails, Salesforce stops the polling. In some cases, the solution is for the administrator to resume the data capture process, but first check the status of the data capture process.

*Check the status of the data capture process*

A symptom that the data capture process failed is the status of the job execution can be *Waiting*  To check the status of the data capture process, execute the following SOQL in the developer console:

----
SELECT Id, Name, SubmittedAt, StartedAt, FinishedAt, ProcessAfter, Status, Error
FROM BackgroundOperation WHERE Name = 'acm_pkg__AnypointContracts__x' ORDER by SubmittedAt DESC LIMIT 15
----

The following symptoms may occur when the status of data capture process is *Waiting*.

== Not Receiving Emails

API Community Manager sends notification emails when an API contract is approved or revoked. If you are not receiving emails, follow the steps for reviewing the user and automated process permissions.

*Review user permissions*

Ensure that Anypoint user corresponds to the Salesforce administrator that set up the change data capture is an *organization administrator of the master organization*. A common issue is that the user who set up the change data capture is not an organization administrator. This user must be an *organization administrator* of the *master organization* to to view all of the available applications and contracts in the organization. See xref:branded-emails.adoc#configure-data-change-capture[Configure Data Change Capture].

There are no errors using SOQL since the job step could end successfully but no contract updates are not returned.

*Review automated process permissions*

The first step in the change data capture job is to retrieve all of the available contracts with updates. Then, the trigger that is set as part of the branded emails configuration runs when there are contract updates. The trigger is not executed by the same user as the change data capture. In this case, Salesforce uses a user named *Automated Process* and this user is created in Anypoint the first time the user tries to use the ACM Community Bridge. 

If the change data capture did not receive the contract associated with the request API access action after adding the Organization Administrator role in Anypoint for the user who set up the change data capture and you created a test applicationof previous step 3. The problem now is that the moment that the “Automated Process” tries to get the contract/application information from Anypoint inside the apex trigger, it will fail since it doesn’t have permission to see all contracts/applications of the organization. So go to Access Management in the Anypoint Platform again, search for the “Automated Process” user and assign the *organization administrator role in the master organization*.

== Change Data Capture Process Displays Errors

An unexpected error occurred while getting contracts in the ACM Community Bridge. For example, an internal Anypoint service is unavailable due to an outage. 

----
Problem querying for changes. An error occurred while connecting to the external system. Please try again, or contact your administrator.
----
 
To resolve, restart the change data capture process by removing and adding again the AnypointContracts entity from *Setup > Integrations > Change Data Capture*. Ensure that you save before adding the entity again.

== Timeout Error is Too Long or OData Query Result is Too Large

If you receive any of the following errors, your organization might have too many client applications or contracts. This causes a timeout to occur because the amount of time that the ACM Community Bridge takes to get this information is greater than the Salesforce timeout of less than two minutes. 

---- 
Error is too long
Problem querying for changes. The OData query result was too large, so the external data didn't load. If the error persists, contact Salesforce Customer Support.
Problem querying for changes. The remote operation timed out. Try again later. If the error persists, contact Salesforce Customer Support.
----

To resolve, check the number of applications that your organization contains using the following curl command with a token from an organization administrator of the master organization. Replace MASTER_ORGANIZATION_ID with your organization ID.

----
curl --location --request GET "https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/${MASTER_ORGANIZATION_ID}/applications?targetAdminSite=true" --header "Authorization: bearer ${TOKEN}"
----

Check the number of applications that your organization has using the following curl command with a token from an organization administrator of the master organization. Replace MASTER_ORGANIZATION_ID with your organization ID. There is an issue if the amount of applications is greater than 2000.

API Community Manager currently limits the amount of applications and contracts contracts because of the way API Manager serves this information. 

To resolve the timeout error:

. To view which contracts have changed in the last X number of minutes, do the following:

.. To get ALL available applications of the master organization (one API call per page of 250 applications, use the following command:
+
---- 
GET https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/${MASTER_ORGANIZATION_ID}/applications?targetAdminSite=true
----
.. To get all the contracts associated with each application (one API call per application), use the following command:
+
----
GET https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/${MASTER_ORGANIZATION_ID}/applications/${APP_ID}/contracts
----
. Filter contracts by memory according to the delta token windows (last  5 minutes).

. Delete the unnecessary applications. 