= Update API Community Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Keep your Anypoint API Community Manager instance up to date to take advantage of new and improved functionality in your community.

For information about updates, see xref:notifications.adoc[Important Notifications].

After you install an update with this process, it is not possible to undo the installation and return to a previous version. Follow this best-practice workflow:

. Keep a partial copy sandbox or a full copy sandbox as a long-term staging environment.
+
The staging environment will have a partial or full copy of the data in the production environment.
. Create a short-term developer sandbox.
. Install the update in the developer sandbox and test it.
. Discard the developer sandbox.
. Install the update in the staging sandbox and test it.
. Install the update in your production environment.

To update your API community:

. Ensure that your Salesforce organizations have the External Data Change Tracking for OData 4.0 Adapter feature enabled:
.. Before upgrading the package in your production or sandbox organization, check that your organization has this feature enabled by going to *Setup* > *External Data Source* and editing the Exchange data source.
.. If you don't see an *Eligible for External Change Data Capture* checkbox, raise a support case through the MuleSoft support portal and list the IDs of all your Salesforce API Community Manager organizations, including the IDs of all production and sandbox organizations.
+
Attempting to upgrade the package without this feature enabled causes the process to fail with errors due to missing objects and fields related to a missing ChangeEvent object.
. Open the API Community Manager control panel.
. In the same browser session, open the *package update installation link* provided by your MuleSoft representative.
. Verify the version number and name of the release.
. If you are upgrading from a package version before 1.26, follow these steps:
.. Go to Salesforce Workbench: https://workbench.developerforce.com/
.. Select Standard.
.. Enter your username and password.
.. Click the Login button.
.. In the Queries menu, click SOQL Query.
.. In the Object list, select *NavigationLinkSet*.
.. In the Fields list, select *Id* and *MasterLabel*.
.. Click the Query button.
.. The query results are displayed as a list of records.
.. Find the records with the *MasterLabel* field set to *NTO_Nav0* and *acm_template_Nav0*.
.. Click the *Id* of the record with the *MasterLabel* field *NTO_Nav0*.
.. Click the Delete button.
.. Click the Confirm delete button.
.. Click the *Id* of the record with the *MasterLabel* field *acm_template_Nav0*.
.. Click the Delete button.
.. Click the Confirm delete button.
.. Continue with normal package installation.
. Select *Install for admins only*.
. Select *Upgrade*.
+
This starts the installation process.
+
When the upgrade finishes, you receive a notification email.
. If you are upgrading from package version 1.62 or earlier, after installing, ensure both `Member` and `Guest` profiles have field-level `Read` access to the `ParentId` field in the `CommunityAPI` object:
.. Configure the `Member` profile:
... Click *Setup* > *Profiles*.
... Open the `Member` profile.
... Click *Object settings* > *CommunityAPI*.
... Ensure the `ParentId` field has `Read` access.
... Save.
.. Configure the `Guest` profile:
... Click *Community builder* > *Settings* > *General*.
... Open the `Guest` profile.
... Click *Object settings* > *CommunityAPI*.
... Ensure the `ParentId` field has `Read` access.
... Save.
. If you are upgrading to package version 1.68, update the permissions of the `Member` and `Guest` profiles on the *SelfRegisterUserRequests* object:
.. Configure the `Member` profile permissions:
... Click *Setup* > *Profiles*.
... Open the `Member` profile.
... Click *Object settings* > *SelfRegisterUserRequests*.
... Ensure there are no object level permissions and no field level permissions for this profile on this object.
.. Configure the `Guest` profile permissions:
... Open the community builder.
... Click *Settings* > *General*.
... Open the `Guest` profile.
... Click *Object settings* > *SelfRegisterUserRequests*.
... Ensure that object level permissions include only `Create` and `Read`.
... Ensure that field level permissions for all fields include only `Read` and `Edit`.
.. Check that your permissions match those in the xref:create-community.adoc#configure-profiles-and-permissions[Configure Profiles and Permissions] documentation.
